export type Status = 'known' | 'revision' | 'unknown' | 'unset';

export interface Reaction {
  id: string;
  num?: string;
  eq: string;
  tip: string;
}

export interface Category {
  id: string;
  name: string;
  desc: string;
  reactions: Reaction[];
}

export const CATEGORIES: Category[] = [
  {
    id: 'hydrolysis',
    name: 'Hydrolysis Reactions (Compounds + H₂O)',
    desc: 'Reactions 75–141 — Oxides, halides, and acids reacting with water',
    reactions: [
      { id: 'R75',  num: '75',  eq: 'B₂O₃ + H₂O → H₃BO₃ → H[B(OH)₄]⁻ + H⁺',                        tip: 'Boron oxide is anhydrous boric acid — reverse to remember.' },
      { id: 'R76',  num: '76',  eq: 'SO₃ + H₂O → H₂SO₄',                                              tip: 'ACID RAIN! SO₃ + water = sulfuric acid. S is +6 in both.' },
      { id: 'R77',  num: '77',  eq: 'BF₃ + H₂O → H₃BO₃ + H[BF₄]⁻',                                   tip: 'BF₃ is a Lewis acid — attacks O of water. One F stays as tetrafluoroborate.' },
      { id: 'R78',  num: '78',  eq: 'KTeF₅ + H₂O → H₂TeO₄ + HF',                                      tip: 'All F atoms leave as HF; Te forms its oxyacid.' },
      { id: 'R79',  num: '79',  eq: 'H₄P₂O₅ + H₂O → 2H₃PO₃',                                         tip: '"Pyro" + water = 2 × "Ortho". Pyrophosphorous → 2 phosphorous acids (P+3).' },
      { id: 'R80',  num: '80',  eq: 'CO + H₂O → No reaction (at RT)',                                  tip: 'C≡O bond is very stable. Steam reforming needs ~1000°C + catalyst.' },
      { id: 'R81',  num: '81',  eq: 'SO₂ + H₂O → H₂SO₃',                                              tip: 'SO₂ → H₂SO₃ (sulfurOUS), SO₃ → H₂SO₄ (sulfuRIC). "-ous" = lower oxidation.' },
      { id: 'R82',  num: '82',  eq: 'H₄P₂O₇ + H₂O → 2H₃PO₄',                                         tip: 'Pyrophosphoric (P+5) → 2 orthophosphoric acids. Two H₃PO₄ joined via P–O–P.' },
      { id: 'R83',  num: '83',  eq: 'BCl₃ + H₂O → H₃BO₃ + 3HCl',                                     tip: 'All 3 Cl leave as HCl, B forms boric acid.' },
      { id: 'R84',  num: '84',  eq: 'IF₅ + H₂O → HIO₃ + 5HF',                                         tip: 'I+5 → iodic acid (I+5). All F leave as HF. Oxidation state unchanged.' },
      { id: 'R85',  num: '85',  eq: 'CO₂ + H₂O → H₂CO₃',                                              tip: 'Soda water! CO₂ = carbonic acid. Why carbonated drinks are acidic.' },
      { id: 'R86',  num: '86',  eq: 'Cl₂O + H₂O → 2HClO',                                             tip: 'Cl₂O is the anhydride of HClO (hypochlorous acid).' },
      { id: 'R87',  num: '87',  eq: 'H₄P₂O₅ + H₂O → 2H₃PO₃',                                         tip: 'Pyrophosphorous → 2 phosphorous acids. The P–O–P bridge breaks in water.' },
      { id: 'R88',  num: '88',  eq: 'CCl₄ + H₂O → No reaction',                                       tip: 'KEY: C has NO d-orbitals. Compare: SiCl₄ DOES react (Si has d-orbitals).' },
      { id: 'R89',  num: '89',  eq: 'ClF₃ + H₂O → HClO₂ + 3HF',                                      tip: 'Cl stays +3. All F leave as HF. ClF₃ → Cl(+3) oxyacid pattern.' },
      { id: 'R90',  num: '90',  eq: 'N₂O + H₂O → No reaction',                                        tip: 'Laughing gas is stable. N has no d-orbitals.' },
      { id: 'R91',  num: '91',  eq: 'ClO₂ + H₂O → HClO₃ + HClO₂ (disproportionation)',               tip: 'ClO₂ is an odd-electron radical — disproportionates: Cl goes +5 and +3.' },
      { id: 'R92',  num: '92',  eq: 'H₄P₂O₈ + H₂O → H₃PO₄ + H₂O₂',                                  tip: 'Peroxodiphosphoric acid — O–O peroxo bond breaks, releasing H₂O₂.' },
      { id: 'R93',  num: '93',  eq: 'NF₃ + H₂O → No reaction',                                        tip: 'N has no d-orbitals AND F is more electronegative than N. Contrast: NCl₃ DOES react!' },
      { id: 'R94',  num: '94',  eq: 'BrF₃ + H₂O → HBrO₃ + 3HF',                                      tip: 'All F leave as HF pattern. Br forms bromic acid.' },
      { id: 'R95',  num: '95',  eq: 'BrF₅ + 3H₂O → HBrO₃ + 5HF',                                      tip: 'Reaction 95! Bromine pentafluoride (Br+5) → bromic acid + HF. All 5 F leave as HF.' },
      { id: 'R96',  num: '96',  eq: 'Cl₂O₅ + H₂O → HClO₃ + HClO₄ (disproportionation)',              tip: 'Mixed Cl oxidation states give two different oxyacids.' },
      { id: 'R97',  num: '97',  eq: 'N₂O₄ + H₂O → HNO₃ + HNO₂ (disproportionation)',                 tip: 'N₂O₄ disproportionates: N goes to +5 (HNO₃) and +3 (HNO₂).' },
      { id: 'R98',  num: '98',  eq: 'NCl₃ + H₂O → HOCl + NH₃',                                       tip: 'KEY EXCEPTION: NCl₃ gives HOCl + NH₃ (not HCl + N-oxyacid). N is more electronegative than Cl!' },
      { id: 'R99',  num: '99',  eq: 'IF₇ + H₂O → HIO₄ + 7HF',                                        tip: 'I+7 → periodic acid (I+7). Maximum oxidation → maximum oxyacid.' },
      { id: 'R100', num: '100', eq: 'N₂O₃ + H₂O → 2HNO₂',                                            tip: 'N₂O₃ is the anhydride of HNO₂. MEMORIZE: N₂O₃ ↔ HNO₂.' },
      { id: 'R101', num: '101', eq: 'Cl₂O₇ + H₂O → 2HClO₄',                                          tip: 'Cl₂O₇ is the anhydride of HClO₄ (perchloric acid). Acid anhydride + water = acid × 2.' },
      { id: 'R102', num: '102', eq: 'H₃PO₅ + H₂O → H₃PO₄ + H₂O₂',                                   tip: 'Peroxymonophosphoric acid — peroxo bond breaks → H₂O₂. Rule: peroxyacid → parent acid + H₂O₂.' },
      { id: 'R103', num: '103', eq: 'SiF₄ + H₂O → H₂SiO₃ + 4HF',                                     tip: 'SiF₄ hydrolyzes (Si HAS d-orbitals, unlike C). F leaves as HF.' },
      { id: 'R104', num: '104', eq: 'ICl₃ + H₂O → HIO₃ + 3HCl',                                      tip: 'Cl leaves as HCl (more electronegative than I). I forms iodic acid.' },
      { id: 'R105', num: '105', eq: 'N₂O₅ + H₂O → 2HNO₃',                                            tip: 'N₂O₅ is the anhydride of HNO₃. KEY: N₂O₅ → 2HNO₃. Compare N₂O₃ → 2HNO₂.' },
      { id: 'R106', num: '106', eq: 'I₂O₅ + H₂O → 2HIO₃',                                            tip: 'I₂O₅ is the anhydride of HIO₃. ALSO detects CO: I₂O₅ + 5CO → 5CO₂ + I₂.' },
      { id: 'R107', num: '107', eq: 'H₂SO₅ + H₂O → H₂SO₄ + H₂O₂',                                   tip: "Caro's acid. Rule: any peroxyacid → parent acid + H₂O₂." },
      { id: 'R108', num: '108', eq: 'SiCl₄ + H₂O → H₂SiO₃ + 4HCl',                                  tip: 'SiCl₄ readily hydrolyzes (unlike CCl₄!). Si has empty d-orbitals.' },
      { id: 'R109', num: '109', eq: 'CrO₂Cl₂ + 2H₂O → H₂CrO₄ + 2HCl',                               tip: 'CHROMYL CHLORIDE TEST! CrO₂Cl₂ + water → chromic acid (yellow) + HCl.' },
      { id: 'R110', num: '110', eq: 'N₂O₄ + H₂O → HNO₃ + HNO₂',                                      tip: 'Same as R97. N₂O₄ disproportionates. Important in dinitrogen tetroxide chemistry.' },
      { id: 'R111', num: '111', eq: 'PCl₃ + 3H₂O → H₃PO₃ + 3HCl',                                    tip: 'PCl₃ → phosphorous acid + HCl. Each Cl replaced by OH from water. P stays +3.' },
      { id: 'R112', num: '112', eq: 'ClF₅ + H₂O → HClO₃ + 5HF',                                      tip: 'Cl+5 → chloric acid (Cl+5). All F leave as HF. Oxidation state maintained.' },
      { id: 'R113', num: '113', eq: 'SiO₂ + H₂O → No reaction',                                       tip: 'Silica is a giant covalent solid. Si–O network too stable. (Dissolves in HF though!)' },
      { id: 'R113b', num: '—',  eq: 'H₂S₂O₈ + 2H₂O → 2H₂SO₄ + H₂O₂',                                  tip: "Marshall's acid (peroxodisulfuric) hydrolyzes to H₂SO₄ + H₂O₂. O–O peroxo bond breaks. Distinct from Caro's acid (H₂SO₅)." },
      { id: 'R114', num: '114', eq: 'H₂B₄O₇ + 5H₂O → 4H₃BO₃',                                       tip: 'Borax (tetraborate) → boric acid. How borax dissolves in water.' },
      { id: 'R115', num: '115', eq: 'H₂S₂O₇ + H₂O → 2H₂SO₄',                                         tip: 'OLEUM + water = sulfuric acid. ALWAYS add acid to water, never water to acid!' },
      { id: 'R116', num: '116', eq: 'PCl₅ + H₂O(lim) → POCl₃ + 2HCl; PCl₅ + 4H₂O → H₃PO₄ + 5HCl', tip: 'Stage-wise hydrolysis. Limited water → POCl₃. Excess → H₃PO₄.' },
      { id: 'R117', num: '117', eq: 'ClF + H₂O → HOCl + HF',                                          tip: 'Cl monofluoride → HOCl + HF. F leaves (more electronegative than Cl).' },
      { id: 'R118', num: '118', eq: 'P₄O₁₀ + 6H₂O → 4H₃PO₄',                                         tip: 'P₄O₁₀ (phosphorus pentoxide) = most powerful desiccant! Reacts vigorously with water.' },
      { id: 'R119', num: '119', eq: 'H₂B₂O₄ + H₂O → H₃BO₃ + H₂O₂',                                  tip: 'Peroxoboric acid — O–O peroxo bond breaks, releasing H₂O₂.' },
      { id: 'R120', num: '120', eq: 'H₂Si₂O₅ + H₂O → H₂SiO₃',                                        tip: 'Pyrosilicic → orthosilicic (silicic) acid. Si–O–Si bridge broken by water.' },
      { id: 'R121', num: '121', eq: 'SF₄ + 2H₂O → H₂SO₃ + 4HF',                                      tip: 'S+4 → sulfurous acid (S+4). F leaves as HF. Oxidation state maintained.' },
      { id: 'R122', num: '122', eq: 'BrF + H₂O → HBrO + HF',                                          tip: 'Br monofluoride → hypobromous acid + HF. Pattern: XF → HOX + HF.' },
      { id: 'R123', num: '123', eq: 'H₂S₂O₃ + H⁺/H₂O → S↓ + H₂SO₃',                                 tip: 'Thiosulfate in acid → sulfur precipitates! Basis of thiosulfate instability in acid.' },
      { id: 'R124', num: '124', eq: 'H₂S₂O₅ + H₂O → 2H₂SO₃',                                         tip: 'Pyrosulfurous (metabisulfite) → 2 sulfurous acids. Pyro + water = 2 ortho.' },
      { id: 'R125', num: '125', eq: 'SF₆ + H₂O → No reaction',                                        tip: 'SF₆ is kinetically inert! All 6 positions occupied by electronegative F.' },
      { id: 'R126', num: '126', eq: 'ICl + H₂O → HIO + HCl',                                          tip: 'I monochloride → hypoiodous acid + HCl. Cl more electronegative than I.' },
      { id: 'R127', num: '127', eq: 'P₄O₆ + 6H₂O → 4H₃PO₃',                                          tip: 'Phosphorus trioxide → phosphorous acid. P₄O₆ + water = H₃PO₃ (P+3).' },
      { id: 'R129', num: '129', eq: 'POCl₃ + 3H₂O → H₃PO₄ + 3HCl',                                   tip: 'Phosphoryl chloride → phosphoric acid + HCl. Cl replaced by OH from water.' },
      { id: 'R130', num: '130', eq: 'IOF₅ + 3H₂O → HIO₄ + 5HF',                                      tip: 'Iodine oxyfluoride → periodic acid + HF.' },
      { id: 'R131', num: '131', eq: 'P₄ + H₂O → No reaction',                                         tip: 'White P is stored UNDER water (catches fire in air!) but does NOT react with water.' },
      { id: 'R132', num: '132', eq: 'NaH + H₂O → NaOH + H₂',                                         tip: 'Ionic hydride: H⁻ + H₂O → OH⁻ + H₂. All group 1/2 metal hydrides react this way.' },
      { id: 'R133', num: '133', eq: 'B₂H₆ + 6H₂O → 2H₃BO₃ + 6H₂',                                   tip: 'Diborane hydrolyzes completely → boric acid + H₂. Very reactive with water.' },
      { id: 'R134', num: '134', eq: 'Cl₂ + H₂O ⇌ HOCl + HCl',                                        tip: 'Chlorine water equilibrium! Why chlorinated pools are acidic. Cl₂ disproportionates.' },
      { id: 'R135', num: '135', eq: 'S₈ + H₂O → No reaction',                                         tip: 'Sulfur is insoluble and unreactive with water. Hydrophobic nonmetal.' },
      { id: 'R136', num: '136', eq: 'SOCl₂ + H₂O → SO₂ + 2HCl',                                      tip: 'Thionyl chloride → SO₂ + HCl. Used in organic synthesis RCOOH → RCOCl.' },
      { id: 'R137', num: '137', eq: 'SO₂Cl₂ + 2H₂O → H₂SO₄ + 2HCl',                                 tip: 'Sulfuryl chloride → sulfuric acid + HCl. Both Cl atoms replaced.' },
      { id: 'R138', num: '138', eq: 'SiH₄ + 2H₂O → SiO₂·H₂O + 4H₂',                                 tip: 'Silane hydrolyzes. SiH₄ less stable than CH₄. Si–H bonds react with water.' },
      { id: 'R139', num: '139', eq: 'I₂ + H₂O → No reaction (significant)',                            tip: 'I₂ barely soluble in water. Dissolves in KI as I₃⁻ but I₂ itself barely reacts.' },
      { id: 'R140', num: '140', eq: 'SOF₂ + H₂O → H₂SO₃ + 2HF',                                      tip: 'Thionyl fluoride → sulfurous acid + HF. Same pattern as SOCl₂ but F leaves as HF.' },
      { id: 'R141', num: '141', eq: '2F₂ + 2H₂O → 4HF + O₂ (+ trace O₃)',                            tip: 'UNIQUE! F₂ oxidizes water itself. Only halogen to do this! Releases O₂ from H₂O.' },
      { id: 'R141b', eq: 'OF₂ + H₂O → O₂ + 2HF',                                                     tip: 'Oxygen difluoride (OF₂) hydrolyzes to O₂ + HF. F is more electronegative than O in OF₂ — so it is actually an oxygen fluoride, not an oxygen oxide. Cl₂O = oxide; OF₂ = fluoride of oxygen.' },
      { id: 'R141c', eq: 'AlCl₃ + 3H₂O → Al(OH)₃↓ + 3HCl (hydrolysis)',                             tip: 'AlCl₃ hydrolyzes strongly in water — forms white Al(OH)₃ precipitate. This is why anhydrous AlCl₃ fumes in moist air and why AlCl₃ solution is acidic.' },
    ],
  },
  {
    id: 'metals',
    name: 'Metals & Basic Reactions',
    desc: 'Reactions 142–179 — Metals with H₂O, acids, and redox reactions',
    reactions: [
      { id: 'R142', num: '142', eq: 'C + O₂(excess) → CO₂; C + O₂(limited) → CO',                     tip: 'Excess O₂ → CO₂. Limited O₂ → CO (poisonous!). Complete vs incomplete combustion.' },
      { id: 'R143', num: '143', eq: '3Mg(s) + N₂(g) → Mg₃N₂',                                         tip: 'Mg burns in N₂! Mg₃N₂ + H₂O → Mg(OH)₂ + NH₃. Mg reacts vigorously with N₂.' },
      { id: 'R144', num: '144', eq: 'NaH(s) + H₂O → NaOH + H₂',                                       tip: 'Ionic hydride: H⁻ acts as base. All group 1 and 2 metal hydrides react this way.' },
      { id: 'R145', num: '145', eq: 'CuSO₄(aq.) + Zn(s) → ZnSO₄ + Cu',                                tip: 'Displacement: Zn > Cu in electrochemical series. Blue solution decolourises, Cu deposits.' },
      { id: 'R146', num: '146', eq: '2Na(s) + 2H₂O(l) → 2NaOH + H₂',                                  tip: 'Na reacts violently with water (melts, fizzes). All group 1 metals react with water.' },
      { id: 'R147', num: '147', eq: 'Ca(s) + 2H₂O(l) → Ca(OH)₂ + H₂',                                 tip: 'Calcium reacts steadily (not explosively) with water. Milky Ca(OH)₂ suspension forms.' },
      { id: 'R148', num: '148', eq: 'Mg + 2H₂O(hot/steam) → Mg(OH)₂ + H₂',                            tip: 'Mg reacts slowly with cold water, faster with hot. Steam → MgO + H₂.' },
      { id: 'R149', num: '149', eq: '3Fe(s) + 4H₂O(steam) → Fe₃O₄ + 4H₂',                             tip: 'Fe reacts with STEAM (not cold water). Forms magnetite Fe₃O₄ (mixed oxide).' },
      { id: 'R150', num: '150', eq: 'Zn(s) + 2HCl → ZnCl₂ + H₂',                                      tip: 'Zn is amphoteric — reacts with acids AND alkalis: Zn + 2NaOH → Na₂ZnO₂ + H₂.' },
      { id: 'R151', num: '151', eq: 'Mg(s) + 2HCl → MgCl₂ + H₂',                                      tip: 'Mg reacts vigorously with HCl. Reactivity order: Mg > Zn > Fe.' },
      { id: 'R152', num: '152', eq: 'Fe(s) + 2HCl → FeCl₂ + H₂',                                      tip: 'Fe + dilute HCl → Fe²⁺ (FeCl₂), NOT Fe³⁺. H⁺ is mild enough only for Fe²⁺.' },
      { id: 'R153', num: '153', eq: 'Cl₂(g) + 2KI(aq.) → 2KCl + I₂',                                  tip: 'Halogen displacement: Cl₂ displaces I₂. Solution turns brown. Starch-iodide test.' },
      { id: 'R154', num: '154', eq: '2H₂O₂ → 2H₂O + O₂ (MnO₂/heat/light catalyst)',                   tip: 'H₂O₂ is unstable — store in dark bottles. MnO₂ is catalyst. Lab O₂ source.' },
      { id: 'R155', num: '155', eq: 'P₄ + 3NaOH + 3H₂O → PH₃ + 3NaH₂PO₂',                           tip: 'White P disproportionates in alkali → phosphine (PH₃) + sodium hypophosphite.' },
      { id: 'R155b', num: '—',  eq: '2Li + 2H₂O → 2LiOH + H₂',                                        tip: 'Li reacts steadily with water — slower than Na. ALL group 1 metals react with water. Li → LiOH + H₂.' },
      { id: 'R156', num: '156', eq: 'S₈ + NaOH(aq.) → Na₂S + Na₂S₂O₃ + H₂O (disproportionation)',   tip: 'Reaction 156! Sulfur disproportionates in alkali. S → S²⁻ (Na₂S) and S₂O₃²⁻ (thiosulfate). 4S + 6NaOH → 2Na₂S + Na₂S₂O₃ + 3H₂O.' },
      { id: 'R157', num: '157', eq: 'Cl₂ + 2NaOH(cold, dil.) → NaCl + NaOCl + H₂O',                  tip: 'Cold dilute NaOH + Cl₂ → NaOCl (bleach). Hot conc NaOH → NaClO₃. Temperature matters!' },
      { id: 'R158', num: '158', eq: 'I₂ + 2NaOH → NaI + NaOI + H₂O',                                 tip: 'Iodine in NaOH → hypoiodite. Pattern: X₂ + 2NaOH → NaX + NaOX.' },
      { id: 'R159', num: '159', eq: 'Pb₃O₄ + 4HCl(dil.) → 2PbCl₂ + Cl₂ + 2H₂O',                     tip: 'Red lead (Pb₃O₄ = 2PbO·PbO₂). PbO₂ part oxidizes Cl⁻ to Cl₂. Compare R160.' },
      { id: 'R160', num: '160', eq: 'Pb₃O₄ + 4HNO₃(dil.) → Pb(NO₃)₂ + PbO₂ + 2H₂O',                tip: 'With HNO₃ — no Cl⁻ to oxidize, PbO₂ stays as solid. Acid-base only, no redox.' },
      { id: 'R161', num: '161', eq: 'PbO₂ + 4HCl(dil.) → PbCl₂ + Cl₂ + 2H₂O',                       tip: 'Lead dioxide (Pb⁴⁺) oxidizes Cl⁻ to Cl₂. Pb⁴⁺ → Pb²⁺. PbO₂ is a strong oxidant.' },
      { id: 'R162', num: '162', eq: 'Cr₂O₇²⁻ + H⁺ + SO₃²⁻ → 2Cr³⁺ + SO₄²⁻',                        tip: 'Dichromate oxidizes sulfite. Cr(+6) → Cr(+3): orange → green.' },
      { id: 'R163', num: '163', eq: 'MnO₄⁻ + H⁺ + Br⁻ → Mn²⁺ + Br₂',                                 tip: 'Permanganate (purple) oxidizes Br⁻ to Br₂. Acidic KMnO₄ is a powerful oxidant.' },
      { id: 'R164', num: '164', eq: 'Fe²⁺(aq.) + Cr₂O₇²⁻ + H⁺ → Fe³⁺(aq.) + Cr³⁺',                  tip: 'Dichromate oxidizes Fe²⁺ to Fe³⁺. Classic volumetric analysis (6 Fe²⁺ per Cr₂O₇²⁻).' },
      { id: 'R165', num: '165', eq: 'I₂ + 2S₂O₃²⁻ → 2I⁻ + S₄O₆²⁻',                                  tip: 'IODOMETRIC TITRATION! Thiosulfate reduces iodine. S₂O₃²⁻ → S₄O₆²⁻ (tetrathionate).' },
      { id: 'R166', num: '166', eq: '2Cu²⁺(aq.) + 4I⁻ → 2CuI↓ + I₂',                                 tip: 'Cu²⁺ oxidizes I⁻ to I₂. Cu²⁺ → Cu⁺ (CuI, white ppt). Used iodometrically for Cu²⁺.' },
      { id: 'R167', num: '167', eq: 'CuO + H₂ → Cu + H₂O',                                            tip: 'H₂ reduces black CuO → shiny red Cu. Classic reduction reaction.' },
      { id: 'R168', num: '168', eq: 'H₃PO₂ + 2AgNO₃ → 2Ag↓ + H₃PO₃ + 2HNO₃',                        tip: 'Hypophosphorous acid (H₃PO₂) is a strong reducing agent! Reduces Ag⁺ to Ag metal.' },
      { id: 'R169', num: '169', eq: 'H₃PO₂ + 2CuSO₄ + 2H₂O → 2Cu↓ + H₃PO₄ + 2H₂SO₄',              tip: 'Reaction 169! H₃PO₂ reduces Cu²⁺ to Cu metal. Powerful reducing agent: H₃PO₂ (P+1) → H₃PO₄ (P+5).' },
      { id: 'R170', num: '170', eq: '2NaNO₃ → 2NaNO₂ + O₂ (heat ~400°C)',                             tip: 'NaNO₃ → nitrite + O₂ at ~400°C. Compare KNO₃: similarly → KNO₂ + O₂.' },
      { id: 'R171', num: '171', eq: 'N₂O₄ ⇌ 2NO₂ (reversible equilibrium)',                            tip: 'N₂O₄ (colourless) ⇌ 2NO₂ (brown). Higher temp → more NO₂. Classic Le Chatelier demo.' },
      { id: 'R172', num: '172', eq: 'Ca(OH)₂ + Cl₂ → CaOCl₂ (bleaching powder)',                      tip: 'Bleaching powder = Ca(OCl)Cl. Made by passing Cl₂ over slaked lime.' },
      { id: 'R173', num: '173', eq: '6XeF₄ + 12H₂O → 4Xe + 2XeO₃ + 24HF + 3O₂ (violent!)',           tip: 'XeF₄ violently disproportionates! Xe → XeO₃ (toxic, explosive!) and Xe(0).' },
      { id: 'R174', num: '174', eq: 'CO + I₂O₅(s) → CO₂ + I₂ (CO detection test)',                     tip: 'CO detection test! I₂O₅ uniquely detects CO — I₂ formed is visible.' },
      { id: 'R175', num: '175', eq: 'FeCr₂O₄ + Na₂CO₃ + O₂ → Fe₂O₃ + Na₂CrO₄ (fusion)',              tip: 'Industrial Cr extraction. Alkaline fusion: Cr(III) → Cr(VI) chromate.' },
      { id: 'R176', num: '176', eq: 'MnO₂ + 2KOH + O₂ → K₂MnO₄ + H₂O',                               tip: 'STEP 1 of KMnO₄ synthesis. MnO₂ + KOH in air → K₂MnO₄ (green manganate, Mn+6).' },
      { id: 'R177', num: '177', eq: '3K₂MnO₄ + 2H₂O → 2KMnO₄ + MnO₂ + 4KOH (disproportionation)',    tip: 'STEP 2 of KMnO₄. Manganate (Mn+6) → permanganate (Mn+7) + MnO₂ (Mn+4).' },
      { id: 'R178', num: '178', eq: '2KMnO₄ → K₂MnO₄ + MnO₂ + O₂ (heat ~240°C)',                     tip: 'KMnO₄ decomposes on heating — lab O₂ source! Purple → green + black + O₂ gas.' },
      { id: 'R179', num: '179', eq: '4K₂Cr₂O₇ → 4K₂CrO₄ + 2Cr₂O₃ + 3O₂ (heat)',                     tip: 'K₂Cr₂O₇ thermal decomp. Orange → yellow (chromate) + green (Cr₂O₃) + O₂.' },
      { id: 'R180', num: '180', eq: '(NH₄)₂Cr₂O₇ → N₂ + Cr₂O₃ + 4H₂O (VOLCANO reaction!)',          tip: 'REACTION 180 — CHROMIUM VOLCANO! Classic demonstration: orange crystals ignite → green Cr₂O₃ ash + N₂ + steam. Spontaneous once ignited!' },
      { id: 'R180b', num: '—',  eq: 'Zn + 2NaOH(aq.) → Na₂ZnO₂ + H₂ (amphoteric Zn)',               tip: 'Zinc is amphoteric — reacts with BOTH acids (ZnCl₂ + H₂) and alkalis (Na₂ZnO₂ + H₂). Al does the same: Al + NaOH → NaAlO₂ + H₂.' },
      { id: 'R180c', eq: '4Fe(OH)₂ + O₂ + 2H₂O → 4Fe(OH)₃ (rusting mechanism)',                    tip: 'RUSTING! Fe(OH)₂ (white/green) is further oxidised by O₂ to Fe(OH)₃ (rust-red). Fe(OH)₃ → Fe₂O₃·xH₂O (rust). Electrochemical mechanism: Fe anode, O₂ cathode.' },
      { id: 'R180d', eq: 'Cl₂ + H₂S → S↓ + 2HCl (Cl₂ oxidises H₂S)',                               tip: 'Cl₂ is a strong enough oxidant to oxidise H₂S → elemental S. Solution turns turbid (S precipitate). Shows relative oxidising power: Cl₂ > S.' },
      { id: 'R180e', eq: 'SO₂ + H₂O₂ → H₂SO₄ (SO₂ oxidised by H₂O₂)',                              tip: 'H₂O₂ oxidises SO₂ (S+4) → H₂SO₄ (S+6). Used in scrubbers. Shows H₂O₂ as oxidant.' },
      { id: 'R180f', eq: 'Fe + 2FeCl₃ → 3FeCl₂ (comproportionation)',                               tip: 'Fe metal + Fe³⁺ → Fe²⁺! Comproportionation: two oxidation states → intermediate. Fe(0) + Fe(+3) → Fe(+2). Used to prepare FeCl₂. Explains why Fe dissolves in FeCl₃ solution.' },
      { id: 'R180g', eq: '2Cu⁺(aq) → Cu²⁺(aq) + Cu (Cu⁺ disproportionation in water)',             tip: 'Cu⁺ is UNSTABLE in water — instantly disproportionates! Cu(+1) → Cu(+2) + Cu(0). This is why CuCl₂ is common but CuCl dissolves poorly. Cu⁺ is stable ONLY as insoluble CuI, CuCl, Cu₂O.' },
      { id: 'R180h', eq: 'Pb + 2NaOH(conc) → Na₂PbO₂ + H₂ (amphoteric Pb)',                        tip: 'Lead is AMPHOTERIC like Zn, Al! Pb dissolves in concentrated NaOH → plumbate Na₂PbO₂ + H₂. Often missed — Pb, Zn, Al, Sn all amphoteric metals.' },
    ],
  },
  {
    id: 'nitrogen',
    name: 'Nitrogen Chemistry',
    desc: 'N₂ fixation, NH₃ reactions, oxides of nitrogen, azides',
    reactions: [
      { id: 'NR01', eq: '6Li + N₂ → 2Li₃N (room temperature!)',                                        tip: 'Only Li reacts with N₂ at room temp! Diagonal relationship: Li behaves like Mg.' },
      { id: 'NR02', eq: 'N₂ + 3H₂ ⇌ 2NH₃ (Haber: 500°C, 200 atm, Fe/K₂O/Al₂O₃)',                    tip: 'MOST IMPORTANT industrial reaction. Haber-Bosch feeds ~50% of world population.' },
      { id: 'NR03', eq: 'N₂ + O₂ → 2NO (high temp/lightning, endothermic)',                            tip: 'Lightning fixes N₂ as NO! Endothermic. Also Birkeland–Eyde process (arc discharge).' },
      { id: 'NR04', eq: 'Ba(N₃)₂ → Ba + 3N₂ (heat)',                                                  tip: 'Azide decomposition gives pure N₂. Lead azide (Pb(N₃)₂) used in detonators.' },
      { id: 'NR05', num: '185', eq: 'NH₄NO₃ → N₂O + 2H₂O (careful heating)',                          tip: 'NH₄NO₃ → laughing gas (N₂O). DANGER: concentrated NH₄NO₃ can detonate (ANFO).' },
      { id: 'NR06', num: '186', eq: 'NaNO₂ + FeSO₄ + H₂SO₄ → [Fe(H₂O)₅NO]SO₄ (brown ring)',         tip: 'BROWN RING TEST for NO₃⁻. Brown ring at interface of FeSO₄ + conc H₂SO₄.' },
      { id: 'NR07', eq: '8NH₃(excess) + 3Cl₂ → 6NH₄Cl + N₂',                                         tip: 'Excess NH₃ + Cl₂ → NH₄Cl + N₂. The N₂ comes FROM NH₃. NH₃ excess = N₂ formed.' },
      { id: 'NR08', eq: 'NH₃ + 3Cl₂(excess) → NCl₃ + 3HCl',                                          tip: 'Excess Cl₂ → NCl₃ (nitrogen trichloride, dangerous). Opposite condition from NR07.' },
      { id: 'NR09', num: '188', eq: '2Pb(NO₃)₂ → 2PbO + 4NO₂ + O₂ (heat)',                           tip: 'Classic thermal decomp producing brown NO₂ fumes. Used as lab source of NO₂.' },
      { id: 'NR10', num: '183', eq: 'N₂ + O₂ → 2NO (ΔH = +180 kJ/mol, endothermic)',                  tip: 'Produced in car engines at high temperature → smog precursor + acid rain.' },
      { id: 'NR11', num: '187', eq: 'NO + NO₂ ⇌ N₂O₃ (at low temperature)',                            tip: 'Reaction 187! NO + NO₂ combine at low temps → N₂O₃ (dinitrogen trioxide). N₂O₃ is the anhydride of HNO₂.' },
      { id: 'NR12', num: '181', eq: 'NH₄NO₂ → N₂ + 2H₂O (heat)',                                     tip: 'REACTION 181 — MISSING FROM OCR! NH₄NO₂ (ammonium nitrite) → N₂ + H₂O. Lab prep of pure N₂. VERY IMPORTANT!' },
      { id: 'NR13', eq: '2NH₄NO₃ → 2N₂ + 4H₂O + O₂ (>300°C, explosive)',                             tip: 'HIGH TEMPERATURE NH₄NO₃ decomp → N₂ + O₂. ANFO explosive! Compare: at ~250°C → N₂O + 2H₂O (milder, NR05).' },
      { id: 'NR14', eq: 'NH₄Cl → NH₃(g) + HCl(g) (thermal dissociation/sublimation)',                 tip: 'NH₄Cl sublimes by dissociation on heating. Reverse of OS06. NH₄Cl deposits on cool surfaces above a flame.' },
      { id: 'NR15', eq: 'NH₄Cl + NaOH → NaCl + NH₃↑ + H₂O',                                         tip: 'Ammonium salt + strong base → NH₃ gas (test for NH₄⁺). Heat required. General: NH₄X + MOH → MX + NH₃ + H₂O.' },
      { id: 'NR16', eq: '(NH₄)₂SO₄ + Ca(OH)₂ → CaSO₄ + 2NH₃↑ + 2H₂O',                             tip: 'Industrial NH₃ recovery from ammonium sulfate (Solvay by-product) using lime. Classic Solvay-related step.' },
      { id: 'NR17', eq: '2KNO₃ → 2KNO₂ + O₂ (heat ~400°C)',                                         tip: 'KNO₃ thermal decomp → potassium nitrite + O₂. Same pattern as NaNO₃ (R170). KNO₃ used in gunpowder (O₂ source).' },
      { id: 'NR18', eq: '3HNO₂ → HNO₃ + 2NO + H₂O (HNO₂ disproportionation)',                      tip: 'Nitrous acid (HNO₂) is unstable — disproportionates on warming. N+3 → N+5 (HNO₃) and N+2 (NO). This is why HNO₂ solution must be freshly prepared.' },
      { id: 'NR19', eq: '2NO₂ + 2NaOH → NaNO₃ + NaNO₂ + H₂O (NO₂ in alkali)',                      tip: 'NO₂ disproportionates in NaOH. N+4 → N+5 (NO₃⁻) + N+3 (NO₂⁻). Compare: Cl₂+NaOH → NaCl+NaOCl. Same pattern for acid-forming gases in alkali.' },
      { id: 'NR20', eq: '2NO + Cl₂ → 2NOCl (nitrosyl chloride)',                                     tip: 'Nitrosyl chloride (NOCl) = yellow gas, highly reactive. Formed by direct combination. Hydrolyzes: NOCl + H₂O → HNO₂ + HCl.' },
      { id: 'NR21', eq: 'N₂H₄ + O₂ → N₂ + 2H₂O (hydrazine combustion)',                             tip: 'Hydrazine (N₂H₄) burns in O₂ → N₂ + H₂O. Used as rocket fuel! ΔH is very negative. Also: N₂H₄ + 4CuO → N₂ + 4Cu + 4H₂O (reduces CuO).' },
      { id: 'NR22', eq: 'N₂H₄ + 4CuO → N₂ + 4Cu + 3H₂O',                                           tip: 'Hydrazine reduces copper oxide. Used to test for N₂H₄. Cu goes from black (CuO) to shiny red (Cu).' },
    ],
  },
  {
    id: 'phosphorus',
    name: 'Phosphorus Chemistry',
    desc: 'Allotropes, halides, oxyacids, and disproportionation',
    reactions: [
      { id: 'PR01', num: '189', eq: 'P₄ + 6Cl₂(limited) → 4PCl₃',                                     tip: 'Limited Cl₂ → PCl₃. 6 Cl₂ for 4P = 3Cl per P. Kinetic product.' },
      { id: 'PR02', num: '190', eq: 'P₄ + 10Cl₂(excess) → 4PCl₅',                                     tip: 'Excess Cl₂ → PCl₅. 10 Cl₂ for 4P = 5Cl per P. Thermodynamic product.' },
      { id: 'PR03', eq: 'P₄ + 8SOCl₂ → 4PCl₃ + 4SO₂',                                                tip: 'SOCl₂ as Cl₂ source for PCl₃ synthesis. 2 SOCl₂ per P.' },
      { id: 'PR04', eq: 'P₄ + 10SO₂Cl₂ → 4PCl₅ + 10SO₂',                                             tip: 'SO₂Cl₂ gives 5Cl per P → PCl₅. Alternative to Cl₂ gas.' },
      { id: 'PR05', num: '191', eq: 'Ag + PCl₅ → AgCl + PCl₃',                                        tip: 'Ag reduces PCl₅ to PCl₃. Ag oxidized to AgCl. PCl₅ acts as oxidant.' },
      { id: 'PR06', num: '192', eq: 'Sn + PCl₄ → SnCl₂ + PCl₃',                                       tip: 'Sn reduces PCl₄. Sn → SnCl₂. PCl₄ → PCl₃.' },
      { id: 'PR07', num: '193', eq: 'PCl₅ ⇌ PCl₃ + Cl₂ (reversible, heat)',                            tip: 'PCl₅ dissociates on heating. Equilibrium shifts right at high temp.' },
      { id: 'PR08', num: '194', eq: 'Red P + NaOH(aq.) → Na₃PO₃ + PH₃',                               tip: 'Red P disproportionates in alkali → phosphine (PH₃, toxic!) + sodium phosphonate.' },
      { id: 'PR09', num: '195', eq: 'H₃PO₂ → H₃PO₄ + PH₃ (heat ~200°C, disproportionation)',         tip: 'Hypophosphorous acid (P+1) → P+5 and P-3. ONLY monobasic phosphorus acid!' },
      { id: 'PR10', num: '196', eq: 'Se₂Cl₂ → SeCl₂ + Se (disproportionation)',                        tip: 'Diselenium dichloride disproportionates. Analogue of S₂Cl₂.' },
      { id: 'PR11', num: '204', eq: '3PbS + 8HNO₃(dil.) → 3Pb(NO₃)₂ + 3S↓ + 2NO + 4H₂O',           tip: 'PbS + dil HNO₃. S stays as elemental S (not SO₄²⁻) with dilute acid.' },
      { id: 'PR12', num: '205', eq: 'S + HNO₃(dil.) → H₂SO₄ + NO',                                   tip: 'S oxidized to H₂SO₄ by dil HNO₃. Nonmetal + HNO₃ → highest oxyacid of that nonmetal.' },
      { id: 'PR13', eq: '4H₃PO₃ → 3H₃PO₄ + PH₃ (heat ~200°C, disproportionation)',                  tip: 'PHOSPHOROUS ACID (H₃PO₃, P+3) disproportionates. DIFFERENT from hypophosphorous (PR09). H₃PO₃ (P+3) → H₃PO₄ (P+5) + PH₃ (P-3). Both are monobasic? No — H₃PO₃ is dibasic!' },
      { id: 'PR14', eq: '4P + 5O₂(excess) → P₄O₁₀ (complete combustion, white phosphorus)',          tip: 'White P burns in excess O₂ → P₄O₁₀ (phosphorus pentoxide). Very vigorous. P₄O₁₀ is powerful desiccant.' },
      { id: 'PR15', eq: '4P + 3O₂(limited) → P₄O₆ (limited O₂, phosphorus trioxide)',               tip: 'Limited O₂ + white P → P₄O₆ (phosphorus trioxide). Excess O₂ → P₄O₁₀ (pentoxide). Like C: limited O₂ gives lower oxide.' },
    ],
  },
  {
    id: 'pcl5',
    name: 'PCl₅ Reactions',
    desc: 'Phosphorus pentachloride as halogenating and chlorinating agent',
    reactions: [
      { id: 'PC01', eq: '2PCl₅ + O₂ → 2POCl₃',                                                        tip: 'PCl₅ oxidized by O₂ → phosphoryl chloride (POCl₃). P=O bond forms.' },
      { id: 'PC02', eq: 'PCl₅ + CO₂ → No reaction',                                                    tip: 'PCl₅ does not react with CO₂. CO₂ is already maximally oxidized.' },
      { id: 'PC03', eq: 'PCl₅ + CH₃COOH → CH₃COCl + POCl₃ + HCl',                                    tip: 'PCl₅ converts –COOH to –COCl (acid chloride). KEY organic synthesis: OH → Cl.' },
      { id: 'PC04', eq: 'PCl₅ + H₃BO₃ → POCl₃ + B₂O₃ + HCl',                                         tip: 'Boric acid + PCl₅. OH groups replaced → POCl₃ + B₂O₃. P gets O from boric acid.' },
      { id: 'PC05', eq: 'PCl₅ + SO₂Cl₂ → PCl₃ + SO₂',                                                 tip: 'SO₂Cl₂ donates Cl context. Check the reaction direction carefully.' },
      { id: 'PC06', eq: 'P₄O₁₀ + 6NaCl → 4POCl₃ + 3Na₂O',                                            tip: 'Alternative synthesis of POCl₃ using P₄O₁₀ and NaCl.' },
      { id: 'PC07', eq: 'PCl₅ + H₂O(lim) → POCl₃ + 2HCl; PCl₅ + 4H₂O → H₃PO₄ + 5HCl',             tip: 'Stage-wise hydrolysis. Limited water → POCl₃. Excess water → H₃PO₄ + 5HCl.' },
      { id: 'PC08', eq: 'PCl₅ + SO₂ → SOCl₂ + POCl₃',                                                 tip: 'PCl₅ chlorinates SO₂ → thionyl chloride (SOCl₂) + POCl₃. Useful synthesis!' },
      { id: 'PC09', eq: 'PCl₅ + SO₃ → SO₂Cl₂ + POCl₃',                                                tip: 'PCl₅ + SO₃ → sulfuryl chloride (SO₂Cl₂) + POCl₃. Compare with PCl₅ + SO₂ → SOCl₂.' },
    ],
  },
  {
    id: 'xenon',
    name: 'Xenon (Noble Gas) Chemistry',
    desc: 'XeF₂, XeF₄, XeF₆ — synthesis, hydrolysis, fluoride ion reactions',
    reactions: [
      { id: 'XR01', eq: 'Xe + F₂ (1:1, Xe excess, 400°C, sealed Ni) → XeF₂',                         tip: 'Xe excess = less F₂. Linear shape (3 lone pairs on Xe). 1:1 → XeF₂.' },
      { id: 'XR02', eq: 'Xe + 2F₂ (1:5 ratio, 400°C, Ni vessel) → XeF₄',                             tip: '1:5 molar ratio → XeF₄. Square planar (2 lone pairs). Pale yellow solid.' },
      { id: 'XR03', eq: 'Xe + 3F₂ (1:20 ratio, 300°C, high pressure) → XeF₆',                        tip: '1:20 large F₂ excess → XeF₆. Distorted octahedral (1 lone pair). Very reactive.' },
      { id: 'XR04', eq: 'XeF₂ + O₂F₂ → XeF₄ + O₂',                                                  tip: 'O₂F₂ is a fluorinating agent. Oxidizes XeF₂ → XeF₄.' },
      { id: 'XR05', eq: '2XeF₂ + 2H₂O → 2Xe + 4HF + O₂',                                            tip: 'XeF₂ hydrolyzes cleanly: Xe → 0 state. O₂ released.' },
      { id: 'XR06', eq: '6XeF₄ + 12H₂O → 4Xe + 2XeO₃ + 24HF + 3O₂ (violent!)',                      tip: 'XeF₄ hydrolysis = violent DISPROPORTIONATION! Xe → XeO₃ (explosive!) and Xe(0).' },
      { id: 'XR07', eq: 'XeF₆ + 3H₂O → XeO₃ + 6HF',                                                  tip: 'XeF₆ fully hydrolyzes to XeO₃ (pyramidal, extremely explosive!) + HF.' },
      { id: 'XR08', eq: 'XeF₄ + H₂O → XeOF₂ + 2HF (partial hydrolysis)',                             tip: 'Partial hydrolysis of XeF₄. Each H₂O replaces 2F with 1O.' },
      { id: 'XR09', eq: 'XeF₆ + 2H₂O → XeO₂F₂ + 4HF (partial hydrolysis)',                           tip: 'Partial hydrolysis of XeF₆. 2H₂O replace 4F with 2O.' },
      { id: 'XR10', eq: 'XeF₄ + PF₅ → [XeF₃]⁺[PF₆]⁻',                                               tip: 'Lewis acid-base: PF₅ accepts F⁻ from XeF₄.' },
      { id: 'XR11', eq: 'XeF₄ + SbF₅ → [XeF₃]⁺[SbF₆]⁻',                                             tip: 'SbF₅ (stronger Lewis acid than PF₅) accepts F⁻. Makes ionic Xe salt.' },
      { id: 'XR12', eq: 'XeF₄ + M⁺F⁻ → M⁺[XeF₅]⁻ (M = Na, K, Rb, Cs)',                             tip: 'Alkali metal fluorides donate F⁻ to XeF₄ → XeF₅⁻. Xe acts as Lewis base.' },
    ],
  },
  {
    id: 'chlorine_special',
    name: 'Special Chlorine Reactions',
    desc: 'Industrial and analytical reactions involving chlorine',
    reactions: [
      { id: 'CL01', eq: 'CH₄ + 2Cl₂(UV, excess) → CHCl₃ + 3HCl',                                    tip: 'Free radical chlorination. Sequential: CH₄ → CH₃Cl → CH₂Cl₂ → CHCl₃ → CCl₄.' },
      { id: 'CL02', eq: '6FeSO₄ + 3Cl₂ + 3H₂SO₄ → 3Fe₂(SO₄)₃ + 6HCl',                             tip: 'Cl₂ oxidizes Fe²⁺ → Fe³⁺. Cl₂ is oxidant, reduced to HCl.' },
      { id: 'CL03', eq: 'I₂ + 5Cl₂ + 6H₂O → 2HIO₃ + 10HCl',                                        tip: 'Cl₂ oxidizes I₂ all the way to iodic acid (I → +5).' },
      { id: 'CL04', eq: 'H₂O + SO₂ + Cl₂ → H₂SO₄ + 2HCl',                                           tip: 'SO₂ oxidized to SO₄²⁻ by Cl₂ + water. HCl also produced.' },
      { id: 'CL05', eq: 'SO₃ + Cl₂ → SO₂Cl₂ (sulfuryl chloride)',                                    tip: 'Direct synthesis of sulfuryl chloride (SO₂Cl₂). Catalyst required.' },
      { id: 'CL06', eq: '2NaCl + 2H₂O → (electrolysis) 2NaOH + Cl₂ + H₂',                           tip: 'CHLORALKALI PROCESS — most important industrial electrolysis.' },
      { id: 'CL07', eq: 'Cl₂O₇ + H₂O → 2HClO₄',                                                      tip: 'Cl₂O₇ is the anhydride of HClO₄ (perchloric acid). Very reactive oily liquid.' },
      { id: 'CL08', eq: '3Cl₂ + 6NaOH(hot, conc.) → 5NaCl + NaClO₃ + 3H₂O',                         tip: 'Hot concentrated NaOH + Cl₂ → chlorate (NaClO₃). Cold dilute → hypochlorite. TEMPERATURE determines product!' },
    ],
  },
  {
    id: 'diborane',
    name: 'Diborane (B₂H₆) & Borazine',
    desc: 'Reactions of diborane and borazine with various reagents',
    reactions: [
      { id: 'BH01', eq: 'B₂H₆ + 6H₂O → 2H₃BO₃ + 6H₂',                                              tip: 'Complete hydrolysis → boric acid + H₂. Very reactive with water.' },
      { id: 'BH02', eq: 'B₃N₃H₆ + 3HCl → B₃N₃H₆Cl₃',                                                tip: 'Borazine (inorganic benzene) reacts with HCl. HCl adds across B–N bonds.' },
      { id: 'BH03', eq: 'B₃N₃H₆ + 9H₂O → 3NH₃ + 3H₃BO₃ + 3H₂',                                     tip: 'Borazine complete hydrolysis → NH₃ + boric acid + H₂. All B–N bonds broken (unlike benzene!).' },
      { id: 'BH04', eq: 'B₂H₆ + 6EtOH → 2B(OEt)₃ + 6H₂',                                            tip: 'Diborane alcoholysis. Each B–H + EtOH → B–OEt + H₂. Forms triethyl borate.' },
      { id: 'BH05', eq: 'B₂H₆ + 2LiH → 2LiBH₄',                                                      tip: 'SYNTHESIS of LiBH₄! Lithium borohydride is a key reducing agent in organic synthesis.' },
      { id: 'BH06', eq: 'B₂H₆ + HCl → B₂H₅Cl + H₂',                                                 tip: 'Mono-chlorination of diborane. One B–H replaced by B–Cl.' },
      { id: 'BH07', eq: 'B₂H₆ + 3Cl₂ → 2BCl₃ + 6HCl',                                               tip: 'Complete chlorination → boron trichloride + HCl. All H atoms replaced by Cl.' },
    ],
  },
  {
    id: 'chromium',
    name: 'Chromium Chemistry',
    desc: 'Extraction, oxidation state equilibria, redox reactions',
    reactions: [
      { id: 'CR01', eq: 'FeCr₂O₄ + 4C → Fe + 2Cr + 4CO (smelting)',                                  tip: 'Chromite ore reduction with carbon at high temp. Gives both Fe and Cr metals.' },
      { id: 'CR02', eq: 'Cr₂O₃ + 2Al → Al₂O₃ + 2Cr (aluminothermite)',                                tip: 'Thermite reaction for pure Cr. Al is a stronger reducing agent. Highly exothermic.' },
      { id: 'CR03', eq: 'CrO₃ + 2HCl → CrO₂Cl₂ + H₂O',                                              tip: 'Chromium trioxide + HCl → chromyl chloride (deep red liquid, b.p. 117°C).' },
      { id: 'CR04', eq: 'K₂Cr₂O₇ + 4KCl + H₂SO₄(conc.) → 2CrO₂Cl₂ + K₂SO₄ + H₂O',                 tip: 'CHROMYL CHLORIDE TEST! Deep red CrO₂Cl₂ vapour confirms Cl⁻. CrO₂Cl₂ + NaOH → yellow CrO₄²⁻.' },
      { id: 'CR05', eq: 'Cr₂O₇²⁻ + 14H⁺ + 6e⁻ → 2Cr³⁺ + 7H₂O (E° = +1.33V)',                       tip: 'Strong oxidant (E° = +1.33V). Orange → green. Balance: 6e⁻ for 2 Cr (+6→+3 = 3e⁻ each).' },
      { id: 'CR06', eq: 'HCrO₄⁻ ⇌ CrO₄²⁻ + H⁺ (pH > 6 → yellow CrO₄²⁻)',                           tip: 'Basic → CrO₄²⁻ (yellow), acidic → Cr₂O₇²⁻ (orange). Add acid: yellow → orange.' },
      { id: 'CR07', eq: '2HCrO₄⁻ ⇌ Cr₂O₇²⁻ + H₂O (pH 2–6 equilibrium)',                             tip: 'Chromate–dichromate interconversion. Acidify CrO₄²⁻ → Cr₂O₇²⁻. Alkalify → CrO₄²⁻.' },
      { id: 'CR08', eq: 'FeCr₂O₄ + Na₂CO₃ + O₂ → Fe₂O₃ + Na₂CrO₄ (alkaline fusion)',                 tip: 'Industrial Cr extraction. Cr(III) → Cr(VI) chromate by alkaline fusion in air.' },
      { id: 'CR09', eq: 'Cr₂O₇²⁻ + OH⁻ ⇌ HCrO₄⁻ + CrO₄²⁻ (base hydrolysis)',                        tip: 'Adding base to dichromate converts it toward chromate. Orange → yellow.' },
      { id: 'CR10', eq: 'HCrO₄⁻ + 2H₂O₂ + H⁺ → CrO(O₂)₂ + 3H₂O (blue peroxochromate)',             tip: 'BLUE PEROXOCHROMATE TEST for Cr! Add H₂O₂ to acidic Cr solution → vivid BLUE CrO(O₂)₂ (chromium blue). Brief but diagnostic.' },
      { id: 'CR11', eq: '2HCrO₄⁻ + 3H₂O₂ + 8H⁺ → 2Cr³⁺ + 3O₂ + 8H₂O (overall)',                   tip: 'Overall reaction of dichromate + H₂O₂ in acid. Blue intermediate forms briefly then decomposes to Cr³⁺ + O₂.' },
      { id: 'CR12', eq: 'HCrO₄⁻ + OH⁻ → CrO₄²⁻ + H₂O',                                              tip: 'In alkaline medium, HCrO₄⁻ (exists at pH 2–6) converts fully to CrO₄²⁻ (yellow).' },
      { id: 'CR13', eq: 'CrO₃Cl⁻ + H₂O → HCrO₄⁻ + H⁺ + Cl⁻ (hydrolysis of chlorochromate)',        tip: 'Chlorochromate ion hydrolyzes back to HCrO₄⁻. Orange potassium chlorochromate KCrO₃Cl in water → chromate.' },
      { id: 'CR14', eq: '2[Cr(OH)₄]⁻ + 3H₂O₂ → 2CrO₄²⁻ + 8H₂O (Cr³⁺→Cr⁶⁺ in alk. H₂O₂)',       tip: 'Cr³⁺ oxidised to Cr⁶⁺ by H₂O₂ in alkaline solution → yellow CrO₄²⁻. Confirms Cr presence. Green → yellow.' },
    ],
  },
  {
    id: 'conc_acids',
    name: 'Reactions with Conc. H₂SO₄ & HNO₃',
    desc: 'Salts, metals, and nonmetals with concentrated acids',
    reactions: [
      { id: 'CA01', num: '197', eq: 'Na₂S + H₂SO₄(conc.) → S↓ + SO₂ + Na₂SO₄',                      tip: 'Conc H₂SO₄ oxidizes S²⁻ → S(0). H₂SO₄ acts as both acid and oxidant.' },
      { id: 'CA02', num: '198', eq: 'MnO₂ + 2NaCl + 2H₂SO₄(conc.) → MnSO₄ + Cl₂ + Na₂SO₄ + 2H₂O', tip: 'LAB PREP of Cl₂! MnO₂ is oxidant (Mn+4 → Mn+2), NaCl provides Cl⁻ → Cl₂.' },
      { id: 'CA03', num: '199', eq: 'NaBr + MnO₂ + H₂SO₄(conc.) → MnSO₄ + Br₂',                     tip: 'Similar to Cl₂ prep but gives Br₂. With just conc H₂SO₄ alone, NaBr → HBr + SO₂.' },
      { id: 'CA04', num: '200', eq: 'NaI + H₂SO₄(conc.) → Na₂SO₄ + I₂ + SO₂ + H₂O',                tip: 'I⁻ is so reducing it reduces H₂SO₄ itself to SO₂! Unlike Cl⁻ (just HCl).' },
      { id: 'CA05', num: '201', eq: 'NaI + MnO₂ + H₂SO₄(conc.) → MnSO₄ + I₂',                       tip: 'MnO₂ + H₂SO₄ oxidizes I⁻ → I₂. Alternative to using just H₂SO₄ alone.' },
      { id: 'CA06', num: '202', eq: 'NaNO₂ + H₂SO₄(conc.) → Na₂SO₄ + NO₂ + O₂ + H₂O',              tip: 'Nitrite + conc H₂SO₄ → NO₂ (brown gas) + O₂. Nitrite is unstable in strong acid.' },
      { id: 'CA07', num: '203', eq: 'Na₂C₂O₄ + H₂SO₄(conc.) → Na₂SO₄ + CO + CO₂ + H₂O',            tip: 'Oxalate + conc H₂SO₄ → CO + CO₂ mixture.' },
      { id: 'CA08', eq: 'Metal + Conc. HNO₃ → Metal nitrate + NO₂ (brown gas)',                        tip: 'RULE: Conc HNO₃ + most metals → NO₂ (brown). Exception: Fe, Al, Cr → passivation.' },
      { id: 'CA09', eq: 'Metal + Dil. HNO₃ → Metal nitrate + NO (colourless)',                         tip: 'RULE: Dil HNO₃ + most metals → NO (colourless). Very dilute + active metal → NH₄⁺.' },
      { id: 'CA10', eq: 'Zn + V.Dil. HNO₃ → Zn(NO₃)₂ + NH₄NO₃ + H₂O',                              tip: 'Very dilute HNO₃ + active metals (Zn, Mg) → NH₄⁺. N reduced from +5 to -3.' },
      { id: 'CA11', eq: 'Fe/Al/Cr/Ni + Conc. HNO₃ → Passivation (protective oxide layer)',            tip: 'Fe, Al, Cr, AND Ni form passive oxide layer with conc HNO₃. Conc HNO₃ stored in Al/steel tanks! Ni is often missed — it also passivates.' },
      { id: 'CA12', eq: '3Ag + 4HNO₃(dil.) → 3AgNO₃ + NO + 2H₂O',                                   tip: 'Ag dissolves in HNO₃ (not HCl — AgCl is insoluble). Balance: 3Ag : 4HNO₃.' },
      { id: 'CA13', eq: 'Ag + 2HNO₃(conc.) → AgNO₃ + NO₂ + H₂O',                                    tip: 'Ag with conc HNO₃ → NO₂. Ag is noble but still dissolves in HNO₃. Dil → NO, Conc → NO₂.' },
      { id: 'CA14', eq: 'Cu + 4HNO₃(conc.) → Cu(NO₃)₂ + 2NO₂ + 2H₂O',                               tip: 'Cu dissolves in HNO₃ (not HCl!). Conc → NO₂. Blue Cu(NO₃)₂ forms. 1Cu:4HNO₃.' },
      { id: 'CA15', eq: '3Cu + 8HNO₃(dil.) → 3Cu(NO₃)₂ + 2NO + 4H₂O',                               tip: 'Cu + dil HNO₃ → NO. Blue solution. MEMORIZE: 3Cu : 8HNO₃.' },
      { id: 'CA16', eq: 'Cu + 2H₂SO₄(conc., hot) → CuSO₄ + SO₂ + 2H₂O',                             tip: 'Cu dissolves in HOT conc H₂SO₄ → blue CuSO₄ + SO₂ (pungent). Cu cannot displace H₂ from acid but conc H₂SO₄ is an oxidizing acid.' },
      { id: 'CA17', eq: 'Zn + 2H₂SO₄(conc., hot) → ZnSO₄ + SO₂ + 2H₂O',                             tip: 'Zn + hot conc H₂SO₄ → SO₂. With very concentrated hot acid, more active metals can even give H₂S.' },
      { id: 'CA18', eq: 'S + 2H₂SO₄(conc.) → 3SO₂ + 2H₂O',                                           tip: 'Nonmetal S reacts with conc H₂SO₄. S acts as reductant, H₂SO₄ as oxidant → 3 SO₂ produced.' },
      { id: 'CA19', eq: 'C + 2H₂SO₄(conc., hot) → CO₂ + 2SO₂ + 2H₂O',                               tip: 'Carbon reacts with hot conc H₂SO₄. C oxidized to CO₂; H₂SO₄ reduced to SO₂.' },
      { id: 'CA20', eq: 'Pb + H₂SO₄(dil.) → PbSO₄↓ (insoluble, no further reaction)',                 tip: 'Lead is EXCEPTION to dil H₂SO₄ reaction! PbSO₄ is insoluble → forms protective coat → Pb does NOT dissolve. Lead storage batteries use this property.' },
      { id: 'CA21', eq: '4Zn + 10HNO₃(mod. dil.) → 4Zn(NO₃)₂ + N₂O + 5H₂O',                        tip: 'Zn + MODERATE dilute HNO₃ → N₂O (laughing gas), NOT NO! Zn is special: conc→NO₂, mod dil→N₂O, very dil→NH₄⁺.' },
      { id: 'CA22', eq: 'Pb + 2HCl(dil.) → PbCl₂↓ + H₂ (barely — PbCl₂ slightly soluble)',          tip: 'Pb + HCl is unusual: PbCl₂ is only SLIGHTLY soluble → barely reacts. Contrast Zn, Fe which dissolve completely in HCl.' },
      { id: 'CA23', eq: 'Sn + 4HNO₃(conc.) → SnO₂↓ + 4NO₂ + 2H₂O (metastannic acid)',               tip: 'Sn + conc HNO₃ → SnO₂ (white insoluble beta-stannic acid) + NO₂. Product is OXIDE not salt! Unique to Sn.' },
      { id: 'CA24', eq: '3Sn + 8HNO₃(dil.) → 3Sn(NO₃)₂ + 2NO + 4H₂O',                              tip: 'Sn + dilute HNO₃ → Sn(NO₃)₂ (soluble salt) + NO. Dilute gives salt. Balance: 3Sn : 8HNO₃.' },
      { id: 'CA25', eq: 'NaCl + H₂SO₄(conc., cold) → NaHSO₄ + HCl↑',                               tip: 'Cold conc H₂SO₄ + NaCl → NaHSO₄ + HCl gas (pungent). Classic test to identify Cl⁻ salt. Hot H₂SO₄: 2NaCl + H₂SO₄ → Na₂SO₄ + 2HCl↑.' },
      { id: 'CA26', eq: 'H₂S + H₂SO₄(conc.) → S↓ + SO₂ + 2H₂O',                                    tip: 'H₂S is oxidised by conc H₂SO₄. S precipitates (yellow), SO₂ evolved (pungent). H₂SO₄ is the oxidant.' },
      { id: 'CA27', eq: 'BiCl₃ + H₂O → BiOCl↓ (white) + 2HCl (bismuth oxychloride)',                tip: 'Characteristic BISMUTH reaction! BiCl₃ hydrolyzes to form BiOCl (white precipitate). Used to identify Bi³⁺. BiI₃ similarly → BiOI↓ (yellow).' },
    ],
  },
  {
    id: 's_block_o2',
    name: 's-block Metals with O₂ — Oxides, Peroxides, Superoxides',
    desc: 'Different products depending on metal and O₂ quantity — critical JEE topic',
    reactions: [
      { id: 'SB01', eq: '4Li + O₂ → 2Li₂O (ONLY normal oxide in group 1)',                            tip: 'Li is the ONLY group 1 metal that forms normal oxide (Li₂O) with O₂. Diagonal relationship with Mg.' },
      { id: 'SB02', eq: '4Na + O₂(limited) → 2Na₂O',                                                  tip: 'Limited O₂ + Na → normal oxide Na₂O. Excess O₂ → Na₂O₂ (peroxide). KEY: amount of O₂ determines product for Na.' },
      { id: 'SB03', eq: '2Na + O₂(excess) → Na₂O₂ (sodium peroxide)',                                  tip: 'Excess O₂ + Na → Na₂O₂. Used in breathing apparatus! Reacts with both CO₂ and H₂O to release O₂.' },
      { id: 'SB04', eq: 'K + O₂ → KO₂ (potassium superoxide)',                                         tip: 'K, Rb, Cs form SUPEROXIDES (MO₂) with O₂. Contains O₂⁻ ion (paramagnetic). More efficient O₂ releaser than peroxide.' },
      { id: 'SB05', eq: '2Na₂O₂ + 2H₂O → 4NaOH + O₂',                                               tip: 'Na₂O₂ + water → NaOH + O₂. Used in submarine/spacecraft! Also: Na₂O₂ + H₂O → NaOH + H₂O₂ (then H₂O₂ decomposes).' },
      { id: 'SB06', eq: '2Na₂O₂ + 2CO₂ → 2Na₂CO₃ + O₂',                                             tip: 'KEY USE of Na₂O₂: absorbs exhaled CO₂ AND releases O₂. 4Na₂O₂ → 2Na₂CO₃ + O₂ net: 2CO₂ absorbed, 1 O₂ released.' },
      { id: 'SB07', eq: '4KO₂ + 2H₂O → 4KOH + 3O₂',                                                  tip: 'KO₂ superoxide + water → KOH + O₂. More O₂ per mole than Na₂O₂! Used in breathing masks. 4KO₂ → 3O₂ (vs 2Na₂O₂ → 1O₂).' },
      { id: 'SB08', eq: '4KO₂ + 2CO₂ → 2K₂CO₃ + 3O₂',                                               tip: 'KO₂ absorbs CO₂ AND releases O₂ — ideal for emergency breathing. Very efficient O₂ source.' },
      { id: 'SB09', eq: '2Mg + O₂ → 2MgO (burns with dazzling white flame)',                           tip: 'Mg burns intensely. Do NOT use CO₂ or H₂O fire extinguisher on Mg fires — Mg reacts with both!' },
      { id: 'SB10', eq: '2Mg + CO₂ → 2MgO + C (Mg burns IN CO₂!)',                                    tip: 'Remarkable: Mg is reactive enough to burn INSIDE CO₂! Strips O from CO₂ → white MgO + black carbon soot. Confirms CO₂ extinguisher fails on Mg.' },
      { id: 'SB11', eq: 'Ba + O₂ → BaO₂ (barium peroxide, like Na₂O₂)',                               tip: 'Ba (unlike Ca) forms peroxide BaO₂ directly. Ba behaves more like Na (group 1 trend) than Ca (group 2 trend) for O₂ reactions.' },
      { id: 'SB12', eq: 'Li₃N + 3H₂O → 3LiOH + NH₃',                                                  tip: 'Lithium nitride hydrolysis → LiOH + NH₃. Metal nitrides react with water to give metal hydroxide + ammonia. This is WHY Mg burnt in N₂ can make NH₃ later!' },
      { id: 'SB13', eq: 'Mg₃N₂ + 6H₂O → 3Mg(OH)₂ + 2NH₃',                                           tip: 'Magnesium nitride hydrolysis. Mg burns in N₂ → Mg₃N₂ → add water → NH₃ gas is produced. KEY LINK: N₂ source → ammonia via metals.' },
      { id: 'SB14', eq: 'Ca₃N₂ + 6H₂O → 3Ca(OH)₂ + 2NH₃',                                           tip: 'Calcium nitride hydrolysis. Like Mg₃N₂, Ca₃N₂ + H₂O → Ca(OH)₂ + NH₃. Metal nitride + H₂O = metal hydroxide + NH₃. General pattern.' },
      { id: 'SB15', eq: 'Na₂O₂ + 2HCl → 2NaCl + H₂O₂',                                               tip: 'Na₂O₂ + dilute acid → H₂O₂! Peroxide reacts with acid to give H₂O₂. Used to make H₂O₂ solution. Compare: Na₂O₂ + H₂O → NaOH + H₂O₂.' },
      { id: 'SB16', eq: '2Na + 2C₂H₅OH → 2C₂H₅ONa + H₂ (sodium + ethanol)',                         tip: 'Sodium reacts with alcohols (like water, but slower). Na + ROH → RONa + ½H₂. Sodium ethoxide forms. Why Na is stored in kerosene NOT ethanol!' },
    ],
  },
  {
    id: 'ostwald',
    name: 'Ostwald Process & NH₃ Combustion',
    desc: 'Industrial HNO₃ synthesis steps + key ammonia reactions',
    reactions: [
      { id: 'OS01', eq: '4NH₃ + 5O₂ → 4NO + 6H₂O (Pt/Rh, ~500°C) [Ostwald Step 1]',                 tip: 'OSTWALD STEP 1 — Catalytic oxidation of NH₃. Pt/Rh catalyst, ~500°C. Without catalyst same reaction gives N₂ instead!' },
      { id: 'OS02', eq: '4NH₃ + 3O₂(combustion, no catalyst) → 2N₂ + 6H₂O',                          tip: 'WITHOUT catalyst, NH₃ burns normally → N₂ + H₂O. The Pt catalyst DIVERTS the reaction to give NO. Temperature is key.' },
      { id: 'OS03', eq: '2NO + O₂ → 2NO₂ [Ostwald Step 2]',                                           tip: 'NO (colourless) + O₂ → NO₂ (brown). Spontaneous at room temp. Ostwald Step 2. Why NO₂ appears above industrial sites.' },
      { id: 'OS04', eq: '4NO₂ + O₂ + 2H₂O → 4HNO₃ [Ostwald Step 3]',                                 tip: 'NO₂ absorbed in water → HNO₃. Ostwald Step 3. Gives ~60% HNO₃. Further concentration by distillation.' },
      { id: 'OS05', eq: '3NO₂ + H₂O → 2HNO₃ + NO (absorption, NO recycled)',                          tip: 'Alternative absorption step. The NO produced is RECYCLED back to Step 2 (2NO + O₂ → 2NO₂). Very efficient process.' },
      { id: 'OS06', eq: 'NH₃(g) + HCl(g) → NH₄Cl(s) (white fumes)',                                   tip: 'WHITE FUMES TEST for NH₃! NH₃ + HCl → NH₄Cl white solid. Seen when HCl and NH₃ gas bottles are near each other.' },
      { id: 'OS07', eq: '2NH₃ + 3CuO → N₂ + 3Cu + 3H₂O',                                             tip: 'CuO acts as mild oxidant. NH₃ reduces CuO (black) → Cu (shiny red). N₂ is final N product. Classic lab demo.' },
      { id: 'OS08', eq: 'NH₃ + H₂O ⇌ NH₄⁺ + OH⁻ (Kb = 1.8×10⁻⁵)',                                   tip: 'NH₃ is a weak base. In water it partially ionizes. Kb = 1.8×10⁻⁵. Aqueous NH₃ is NOT NaOH (reversible equilibrium).' },
    ],
  },
  {
    id: 'kmno4',
    name: 'KMnO₄ Reactions — Acidic, Neutral, Alkaline',
    desc: 'Permanganate as oxidant in three different media — key JEE volumetric analysis',
    reactions: [
      { id: 'KM01', eq: '2KMnO₄ + 5H₂C₂O₄ + 3H₂SO₄ → 2MnSO₄ + 10CO₂ + K₂SO₄ + 8H₂O (acidic)',   tip: 'PERMANGANIMETRY! Classic titration — KMnO₄ vs oxalic acid. Self-indicating (purple → colourless). Mn+7 → Mn+2 (5e⁻). Warm to ~70°C to start reaction.' },
      { id: 'KM02', eq: '10FeSO₄ + 2KMnO₄ + 8H₂SO₄ → 5Fe₂(SO₄)₃ + 2MnSO₄ + K₂SO₄ + 8H₂O (acidic)', tip: 'Fe²⁺ estimation by KMnO₄. Acidic medium → Mn²⁺ (colourless). Purple → colourless at endpoint. 5Fe²⁺ per KMnO₄.' },
      { id: 'KM03', eq: '2KMnO₄ + 5H₂O₂ + 3H₂SO₄ → 2MnSO₄ + 5O₂ + K₂SO₄ + 8H₂O (acidic)',        tip: 'H₂O₂ estimation. H₂O₂ acts as REDUCTANT here (also acts as oxidant with KI!). Mn+7 → Mn+2. Purple → colourless.' },
      { id: 'KM04', eq: '2KMnO₄ + 5Na₂SO₃ + 3H₂SO₄ → 2MnSO₄ + 5Na₂SO₄ + K₂SO₄ + 3H₂O (acidic)',  tip: 'KMnO₄ oxidizes sulfite SO₃²⁻ → sulfate SO₄²⁻. Acidic medium: Mn+7 → Mn+2.' },
      { id: 'KM05', eq: '2KMnO₄ + 3Na₂SO₃ + H₂O → 2MnO₂↓ + 3Na₂SO₄ + 2KOH (neutral medium)',       tip: 'NEUTRAL medium: KMnO₄ → MnO₂ (brown precipitate). Mn+7 → Mn+4 (only 3e⁻ gain). Distinguishing feature of neutral KMnO₄.' },
      { id: 'KM06', eq: '2MnO₄⁻ + SO₃²⁻ + 2OH⁻ → 2MnO₄²⁻ + SO₄²⁻ + H₂O (alkaline medium)',        tip: 'ALKALINE medium: KMnO₄ → manganate K₂MnO₄ (green). Mn+7 → Mn+6 (only 1e⁻ gain). Less powerful in alkali.' },
      { id: 'KM07', eq: 'COLOUR GUIDE: Acidic → Mn²⁺ (colourless); Neutral → MnO₂ (brown); Alkaline → MnO₄²⁻ (green)', tip: 'MEMORIZE: KMnO₄ products in 3 media: Acid=Mn²⁺ (colourless, 5e⁻), Neutral=MnO₂ (brown, 3e⁻), Alkali=MnO₄²⁻ (green, 1e⁻).' },
    ],
  },
  {
    id: 'nonmetal_hno3',
    name: 'Non-metals & Metalloids with HNO₃',
    desc: 'S, P, I₂, As, C with concentrated and dilute HNO₃',
    reactions: [
      { id: 'NM01', eq: 'S + 2HNO₃(conc.) → H₂SO₄ + 2NO₂',                                           tip: 'S + CONC HNO₃ → NO₂ (brown gas). Compare: S + dil HNO₃ → NO. Concentration determines which oxide of N forms.' },
      { id: 'NM02', eq: 'P₄ + 20HNO₃(conc.) → 4H₃PO₄ + 20NO₂ + 4H₂O',                              tip: 'P + CONC HNO₃ → phosphoric acid + NO₂. P completely oxidized to +5 state. Dil HNO₃ → NO instead of NO₂.' },
      { id: 'NM03', eq: 'I₂ + 10HNO₃(conc.) → 2HIO₃ + 10NO₂ + 4H₂O',                               tip: 'I₂ + CONC HNO₃ → iodic acid (HIO₃) + NO₂. I oxidized from 0 to +5. Important: same product as Cl₂+H₂O reaction for I₂.' },
      { id: 'NM04', eq: '3I₂ + 10HNO₃(dil.) → 6HIO₃ + 10NO + 2H₂O',                                 tip: 'I₂ + DIL HNO₃ → iodic acid + NO. Dil gives NO (not NO₂). Iodine oxidized to iodic acid regardless of concentration.' },
      { id: 'NM05', eq: 'As + 5HNO₃(conc.) → H₃AsO₄ + 5NO₂ + H₂O',                                  tip: 'Arsenic + CONC HNO₃ → arsenic acid (H₃AsO₄, As+5) + NO₂. Arsenic is fully oxidized.' },
      { id: 'NM06', eq: '3As + 5HNO₃(dil.) + 2H₂O → 3H₃AsO₄ + 5NO',                                 tip: 'Arsenic + DIL HNO₃ → H₃AsO₄ + NO. Dil gives NO. Arsenic acid (H₃AsO₄) is a weak acid.' },
      { id: 'NM07', eq: 'C + 4HNO₃(conc., hot) → CO₂ + 4NO₂ + 2H₂O',                                tip: 'Carbon reacts with HOT conc HNO₃ → CO₂ + NO₂. C is oxidized. Less common reaction but important for completeness.' },
    ],
  },
  {
    id: 'metal_oxides',
    name: 'Metal Oxides & Hydroxide Reactions',
    desc: 'Reactions of metal oxides with water, acids, alkalis — amphoteric behaviour',
    reactions: [
      { id: 'MO01', eq: 'Na₂O + H₂O → 2NaOH',                                                         tip: 'Sodium oxide + water → NaOH (strongly basic). All alkali metal oxides react exothermically with water.' },
      { id: 'MO02', eq: 'CaO + H₂O → Ca(OH)₂ (slaking of lime, very exothermic)',                     tip: 'LIME SLAKING! Quicklime (CaO) + water = slaked lime (Ca(OH)₂). Exothermic — generates steam. Used in cement.' },
      { id: 'MO03', eq: 'CaCO₃ → CaO + CO₂ (calcination, ~900°C)',                                    tip: 'CALCINATION of limestone → quicklime. Basis of cement, glass, steel industries. CaCO₃ loses CO₂ at ~900°C.' },
      { id: 'MO04', eq: 'Ca(OH)₂ + CO₂ → CaCO₃↓ + H₂O',                                              tip: 'LIMEWATER TEST for CO₂! Limewater (Ca(OH)₂ soln) turns MILKY white (CaCO₃ ppt). Classic qualitative test.' },
      { id: 'MO05', eq: 'CaCO₃ + CO₂(excess) + H₂O → Ca(HCO₃)₂ (milky → clear)',                    tip: 'Excess CO₂ dissolves CaCO₃ → soluble Ca(HCO₃)₂. Milky → clear again. WHY: limestone caves form (acidic rainwater dissolves CaCO₃).' },
      { id: 'MO06', eq: 'Al₂O₃ + 2NaOH(conc.) → 2NaAlO₂ + H₂O (amphoteric)',                        tip: 'Alumina dissolves in NaOH — AMPHOTERIC! Al₂O₃ reacts with both acid and alkali. With excess NaOH → Na[Al(OH)₄] (aluminate).' },
      { id: 'MO07', eq: 'Al₂O₃ + 6HCl → 2AlCl₃ + 3H₂O (amphoteric)',                                 tip: 'Alumina dissolves in HCl — AMPHOTERIC! Al₂O₃ + HCl → AlCl₃. Dissolves in both HCl (AlCl₃) and NaOH (NaAlO₂).' },
      { id: 'MO08', eq: '2Al + 2NaOH + 2H₂O → 2NaAlO₂ + 3H₂ (Al metal in NaOH)',                    tip: 'Al metal (not just Al₂O₃) dissolves in NaOH → NaAlO₂ + H₂. Al is amphoteric metal. Used in drain cleaners!' },
      { id: 'MO09', eq: 'CaO + CO₂ → CaCO₃ (quicklime absorbs CO₂)',                                  tip: 'CaO is a CO₂ absorber. Used to remove CO₂ in gas analysis. Reverse of calcination. Drives CaCO₃ decomposition.' },
      { id: 'MO10', eq: 'Fe₂O₃ + 6HCl → 2FeCl₃ + 3H₂O (dissolution of rust)',                        tip: 'Rust (Fe₂O₃) dissolves in HCl. Acidic cleaning of iron/steel. Fe₃O₄ + 8HCl → FeCl₂ + 2FeCl₃ + 4H₂O.' },
      { id: 'MO11', eq: 'CaO + SiO₂ → CaSiO₃ (slag, blast furnace)',                                  tip: 'SLAG FORMATION in blast furnace! Limestone (CaCO₃ → CaO) reacts with silica impurities → CaSiO₃ (slag) which floats on molten iron.' },
      { id: 'MO12', eq: '2Fe(OH)₃ → Fe₂O₃ + 3H₂O (dehydration on heating)',                          tip: 'Fe(OH)₃ (red-brown precipitate) loses water on heating → Fe₂O₃ (red). This is how rust (Fe₂O₃·xH₂O) loses water to form anhydrous Fe₂O₃.' },
      { id: 'MO13', eq: 'Zn(OH)₂ + 2NaOH → Na₂[Zn(OH)₄] (amphoteric Zn hydroxide)',                 tip: 'Zn(OH)₂ is amphoteric. Dissolves in NaOH → zincate ion [Zn(OH)₄]²⁻. Also dissolves in HCl → ZnCl₂ + H₂O. Similar to Al(OH)₃ behaviour.' },
      { id: 'MO14', eq: 'NaAlO₂ + CO₂ + 2H₂O → Al(OH)₃↓ + NaHCO₃ (Bayer process)',                 tip: 'BAYER PROCESS step: aluminate solution + CO₂ → Al(OH)₃ precipitates. CO₂ (weak acid) is enough to precipitate Al(OH)₃ from aluminate solution.' },
      { id: 'MO15', eq: 'Al(OH)₃ + 3HCl → AlCl₃ + 3H₂O (acid side)',                                tip: 'Al(OH)₃ dissolves in HCl. Amphoteric: dissolves in acid (→ AlCl₃) and alkali (→ NaAlO₂). White precipitate dissolves on adding excess HCl.' },
      { id: 'MO16', eq: 'Al(OH)₃ + NaOH → NaAlO₂ + 2H₂O (alkali side)',                             tip: 'Al(OH)₃ dissolves in excess NaOH → aluminate. Amphoteric hydroxide dissolves in both acid and base. Used in Bayer process.' },
      { id: 'MO17', eq: 'Li₂CO₃ → Li₂O + CO₂ (heat, Li₂CO₃ is thermally UNSTABLE)',               tip: 'KEY Advanced: Li₂CO₃ decomposes on heating (like MgCO₃) — UNLIKE Na₂CO₃, K₂CO₃ which are stable! Diagonal relationship: Li behaves like Mg.' },
      { id: 'MO18', eq: 'MgCO₃ → MgO + CO₂ (heat, lower stability than CaCO₃)',                    tip: 'MgCO₃ decomposes at lower temp than CaCO₃. Trend: stability of group 2 carbonates INCREASES down the group. BeCO₃ < MgCO₃ < CaCO₃ < SrCO₃ < BaCO₃.' },
    ],
  },
  {
    id: 'halogen_industrial',
    name: 'Halogen Displacement, Ozone & Industrial Reactions',
    desc: 'Halogen reactivity series, ozone tests, Contact Process, Claus process',
    reactions: [
      { id: 'HI01', eq: 'F₂ + 2NaCl → 2NaF + Cl₂ (F₂ displaces ALL halogens)',                       tip: 'F₂ is the strongest oxidizing halogen — displaces Cl₂, Br₂, I₂ from their salts. Electronegativity: F>Cl>Br>I.' },
      { id: 'HI02', eq: 'Cl₂ + 2NaBr → 2NaCl + Br₂ (Cl₂ displaces Br₂)',                             tip: 'Chlorine displaces bromine. Solution turns orange-brown. Cl₂ is stronger oxidant than Br₂. Classic reactivity demonstration.' },
      { id: 'HI03', eq: 'Br₂ + 2NaI → 2NaBr + I₂ (Br₂ displaces I₂)',                                tip: 'Bromine displaces iodine. Solution turns brown/violet. Br₂ is stronger oxidant than I₂. Reactivity: F₂>Cl₂>Br₂>I₂.' },
      { id: 'HI04', eq: 'Au + 3HCl + HNO₃ → AuCl₃ + NO + 2H₂O (aqua regia)',                        tip: 'AQUA REGIA (3:1 HCl:HNO₃) dissolves GOLD! Neither HCl nor HNO₃ alone can dissolve Au. HNO₃ oxidizes, Cl⁻ forms stable AuCl₄⁻ complex.' },
      { id: 'HI05', eq: 'O₃ + 2KI + H₂O → 2KOH + I₂ + O₂ (ozone test)',                             tip: 'OZONE TEST! O₃ oxidizes KI → I₂ (turns starch paper BLUE). O₂ does NOT do this. Distinguishes O₃ from O₂.' },
      { id: 'HI06', eq: 'SO₂ + 2H₂S → 3S↓ + 2H₂O (Claus reaction)',                                  tip: 'Claus process: SO₂ (oxidant) + H₂S (reductant) → elemental sulfur. Used industrially to recover S from flue gases. S precipitates.' },
      { id: 'HI07', eq: '2SO₂ + O₂ → 2SO₃ (Contact Process, V₂O₅, 450°C)',                           tip: 'CONTACT PROCESS Step 2: V₂O₅ catalyst, 450°C, 1–2 atm. Le Chatelier: lower temp favors SO₃ but V₂O₅ needs 450°C minimum.' },
      { id: 'HI08', eq: 'SO₃ + H₂SO₄ → H₂S₂O₇ (oleum, Contact Process Step 3)',                      tip: 'SO₃ absorbed in conc H₂SO₄ → oleum (H₂S₂O₇). Then diluted with water → 2H₂SO₄. Direct SO₃+H₂O gives acid mist.' },
      { id: 'HI09', eq: 'O₃ + PbS → PbSO₄ (bleaching by O₃)',                                         tip: 'Ozone bleaches by oxidation. Black PbS (lead sulfide) → white PbSO₄. O₃ restores yellowed white lead paintings.' },
      { id: 'HI10', eq: '2O₃ → 3O₂ (thermal/photochemical decomposition)',                             tip: 'Ozone is thermodynamically unstable and decomposes to O₂. Decomposition catalysed by Cl radicals (CFC depletion of ozone layer!).' },
      { id: 'HI11', eq: 'Br₂ + 2NaOH(cold, dil.) → NaBr + NaOBr + H₂O',                             tip: 'Bromine in cold dilute NaOH → NaBr + NaOBr (sodium hypobromite). Pattern: X₂ + 2NaOH(cold) → NaX + NaOX. Hot → NaBrO₃ instead.' },
      { id: 'HI12', eq: '3Br₂ + 6NaOH(hot conc.) → 5NaBr + NaBrO₃ + 3H₂O',                         tip: 'Bromine in HOT concentrated NaOH → bromate (NaBrO₃)! Compare: cold dilute → hypobromite (NaOBr). Temperature is key.' },
      { id: 'HI13', eq: '3I₂ + 6NaOH(hot conc.) → 5NaI + NaIO₃ + 3H₂O',                            tip: 'Iodine in HOT concentrated NaOH → iodate (NaIO₃)! Compare: cold dilute (R158): I₂ + NaOH → NaOI (hypoiodite). Temperature determines product.' },
      { id: 'HI14', eq: 'H₂O₂ + 2KI + H₂SO₄ → I₂ + K₂SO₄ + 2H₂O (H₂O₂ as oxidant)',             tip: 'H₂O₂ oxidizes I⁻ → I₂. H₂O₂ acts as OXIDANT here. Contrast: H₂O₂ is REDUCTANT with KMnO₄ (KM03). H₂O₂ is both — depends on the other reagent!' },
      { id: 'HI15', eq: 'SO₂ + 2NaOH → Na₂SO₃ + H₂O (excess NaOH)',                               tip: 'SO₂ absorbed in excess NaOH → sodium sulfite Na₂SO₃. Limited NaOH: SO₂ + NaOH → NaHSO₃. This is WHY acid rain (SO₂) is treated with NaOH scrubbers!' },
      { id: 'HI16', eq: 'SO₂ + NaOH(limited) → NaHSO₃ (sodium bisulfite)',                         tip: 'Limited NaOH + SO₂ → NaHSO₃ (sodium bisulfite/hydrogensulfite). Excess NaOH → Na₂SO₃. Same pattern as CO₂ + NaOH giving NaHCO₃ or Na₂CO₃.' },
      { id: 'HI17', eq: 'Ca(OH)₂ + SO₂ → CaSO₃↓ + H₂O (SO₂ turns limewater milky)',               tip: 'LIMEWATER TEST for SO₂ (and CO₂)! Both turn limewater milky. Distinguish by smell (SO₂ = pungent, CO₂ = odourless) or by K₂Cr₂O₇ paper (SO₂ turns green; CO₂ does not).' },
      { id: 'HI18', eq: '2F₂ + 4NaOH → 4NaF + 2H₂O + O₂ (F₂ + NaOH ≠ NaF + NaOF)',             tip: 'F₂ + NaOH is NOT like Cl₂+NaOH! F₂ is so strongly oxidising it oxidises OH⁻ → O₂ (not forms NaOF). 2F₂ + 4NaOH → 4NaF + 2H₂O + O₂. NaOF does NOT form.' },
    ],
  },
  {
    id: 'thermite_lab',
    name: 'Thermite, Blast Furnace & Metal+Halogen Reactions',
    desc: 'Metallurgical reductions and metal reactions with halogens',
    reactions: [
      { id: 'TL01', eq: '2Al + Fe₂O₃ → Al₂O₃ + 2Fe (THERMITE reaction, ~2500°C)',                    tip: 'THERMITE REACTION! Produces molten iron. ΔH = -850 kJ/mol. Used to weld railway tracks! Al is stronger reducing agent than Fe.' },
      { id: 'TL02', eq: 'Fe₂O₃ + 3CO → 2Fe + 3CO₂ (blast furnace, ~1500°C)',                         tip: 'BLAST FURNACE reduction of iron ore. CO is the actual reducing agent (from coke + hot air). Steps: C+O₂→CO₂; CO₂+C→2CO; Fe₂O₃+3CO→2Fe.' },
      { id: 'TL03', eq: '2Fe + 3Cl₂ → 2FeCl₃ (Fe + halogen → Fe³⁺, NOT Fe²⁺!)',                     tip: 'KEY! Fe + Cl₂ → FeCl₃ (ferric/iron III). Unlike Fe + HCl → FeCl₂ (ferrous)! Halogens are strong enough to oxidize Fe to +3 state.' },
      { id: 'TL04', eq: '2Al + 3Cl₂ → 2AlCl₃ (ANHYDROUS aluminium chloride)',                        tip: 'Anhydrous AlCl₃ (Lewis acid catalyst!) made by reacting Al metal with Cl₂. AlCl₃ from Al₂O₃+HCl gives hydrated AlCl₃·6H₂O, NOT AlCl₃.' },
      { id: 'TL05', eq: '2Na + Cl₂ → 2NaCl',                                                          tip: 'Na burns in Cl₂ to form NaCl. Vigorous reaction. Similarly K, Ca, Mg all react with Cl₂ directly.' },
      { id: 'TL06', eq: '2Cu + Cl₂ → 2CuCl (excess Cu); Cu + Cl₂ → CuCl₂ (excess Cl₂)',             tip: 'Excess Cu → CuCl (cuprous). Excess Cl₂ → CuCl₂ (cupric). Like P and Cl₂, the ratio matters!' },
      { id: 'TL07', eq: '2Cu + O₂ → 2CuO (black copper oxide)',                                       tip: 'Copper + O₂ → CuO (black). CuO is reduced by H₂ → Cu + H₂O (R167). Reversible oxidation.' },
      { id: 'TL08', eq: '4Cu + O₂ + CO₂ + H₂O → Cu₂(OH)₂CO₃ (verdigris/patina)',                    tip: 'Copper turns green outdoors (Statue of Liberty!). Cu₂(OH)₂CO₃ is basic copper carbonate. Patina = Cu + O₂ + CO₂ + H₂O.' },
      { id: 'TL09', eq: '2FeCl₂ + Cl₂ → 2FeCl₃ (Fe²⁺ oxidised by Cl₂ → Fe³⁺)',                    tip: 'KEY! Cl₂ oxidises Fe²⁺ to Fe³⁺. Used to convert FeCl₂ → FeCl₃. Reverse of FeCl₃+reducing agent→FeCl₂.' },
      { id: 'TL10', eq: 'H₂S + 2FeCl₃ → 2FeCl₂ + S↓ + 2HCl',                                       tip: 'H₂S is a strong enough reducing agent to reduce Fe³⁺ → Fe²⁺. Sulfur precipitates. H₂S is oxidised from −2 to 0.' },
      { id: 'TL11', eq: 'Cu + 2AgNO₃ → Cu(NO₃)₂ + 2Ag (displacement)',                              tip: 'Copper displaces silver from AgNO₃. Blue solution (Cu²⁺) forms + Ag metal deposits. Cu is above Ag in electrochemical series.' },
      { id: 'TL12', eq: 'Sn + CuSO₄ → SnSO₄ + Cu (displacement)',                                   tip: 'Tin displaces copper. Sn is above Cu in electrochemical series. Blue solution decolorises as Cu deposits.' },
      { id: 'TL13', eq: 'K₂Cr₂O₇ + 6FeSO₄ + 7H₂SO₄ → Cr₂(SO₄)₃ + 3Fe₂(SO₄)₃ + K₂SO₄ + 7H₂O',  tip: 'BALANCED dichromate + ferrous reaction. K₂Cr₂O₇ is standard in titrimetry. Cr+6→Cr+3 (gain 6e⁻), Fe+2→Fe+3 (lose 1e⁻ × 6). Orange → green.' },
      { id: 'TL14', eq: 'MnO₂ + 4HCl(conc) → MnCl₂ + Cl₂ + 2H₂O',                               tip: 'DIRECT lab prep of Cl₂! Conc HCl + MnO₂ → Cl₂ gas (pungent yellow-green). Mn+4 → Mn+2; Cl⁻ → Cl₂. Simpler than CA02 (no NaCl or H₂SO₄ needed). Heat required.' },
      { id: 'TL15', eq: '2KMnO₄ + 16HCl → 2KCl + 2MnCl₂ + 5Cl₂ + 8H₂O',                        tip: 'KMnO₄ OXIDISES Cl⁻ to Cl₂ in acidic solution! This is why HCl CANNOT be used to acidify KMnO₄ in permanganate titrations — use H₂SO₄ instead. Mn+7 → Mn+2 (5e⁻); Cl⁻ → Cl₂.' },
    ],
  },
  {
    id: 'lab_preps',
    name: 'Laboratory Preparations & Key Analytical Reactions',
    desc: 'Classic lab preps of gases, H₂O₂ dual nature, thiosulfate chemistry',
    reactions: [
      { id: 'LP01', eq: 'CaCO₃ + 2HCl → CaCl₂ + CO₂ + H₂O (lab CO₂ prep)',                          tip: 'LAB PREP of CO₂! Marble/limestone chips + dilute HCl. Easiest method. Gas collected over water or in a gas syringe.' },
      { id: 'LP02', eq: 'FeS + 2HCl → FeCl₂ + H₂S (lab H₂S prep)',                                   tip: 'LAB PREP of H₂S! Iron sulfide + dilute HCl → H₂S (rotten egg smell, toxic!). H₂S is reducing agent and precipitating agent in qual. analysis.' },
      { id: 'LP03', eq: 'Na₂SO₃ + H₂SO₄(dil.) → Na₂SO₄ + SO₂ + H₂O (lab SO₂ prep)',                tip: 'LAB PREP of SO₂! Sodium sulfite + dilute H₂SO₄ → SO₂ gas. Alternatively: Cu + conc H₂SO₄ → CuSO₄ + SO₂ (CA16).' },
      { id: 'LP04', eq: 'Na₂S₂O₃ + 2HCl → 2NaCl + S↓ + SO₂ + H₂O',                                 tip: 'Thiosulfate + acid → INSTANT sulfur precipitate + SO₂. Classic rate-of-reaction experiment (how fast solution turns cloudy). S₂O₃²⁻ disproportionates in acid.' },
      { id: 'LP05', eq: 'H₂O₂ + 2KI + H₂SO₄ → I₂ + K₂SO₄ + 2H₂O (H₂O₂ = oxidant)',               tip: 'H₂O₂ as OXIDANT: oxidizes I⁻ → I₂. Contrast with KM03 where H₂O₂ is REDUCTANT. H₂O₂ is amphoteric — oxidant with less reactive partners, reductant with stronger oxidants (KMnO₄, Ag₂O).' },
      { id: 'LP06', eq: 'H₂O₂ + Ag₂O → 2Ag + O₂ + H₂O (H₂O₂ = reductant)',                         tip: 'H₂O₂ as REDUCTANT: reduces Ag₂O (Ag+1) → Ag(0) metal. H₂O₂ is oxidized → O₂. Shows the dual nature of H₂O₂.' },
      { id: 'LP07', eq: 'H₂O₂ + H₂S → S↓ + 2H₂O (H₂O₂ oxidizes H₂S)',                               tip: 'H₂O₂ oxidizes H₂S → sulfur + water. H₂O₂ is oxidant here. Used to precipitate S from H₂S gas.' },
      { id: 'LP08', eq: 'Ag⁺ + Cl⁻ → AgCl↓ (white, curdy); AgBr↓ (pale yellow); AgI↓ (yellow)',     tip: 'HALIDE IDENTIFICATION! AgCl = white (soluble in NH₃), AgBr = pale yellow (slightly sol in NH₃), AgI = yellow (insoluble in NH₃). KEY qualitative test.' },
      { id: 'LP09', eq: 'Ba²⁺ + SO₄²⁻ → BaSO₄↓ (white, insoluble in HCl)',                          tip: 'SULFATE IDENTIFICATION! BaSO₄ white precipitate with BaCl₂ solution. Insoluble even in HCl — distinguishes SO₄²⁻ from SO₃²⁻ (BaSO₃ IS soluble in HCl).' },
      { id: 'LP10', eq: 'Pb²⁺ + 2I⁻ → PbI₂↓ (golden yellow — "lead iodide golden rain")',            tip: 'Golden rain experiment! PbI₂ precipitates as beautiful golden yellow crystals. Classic chemistry demonstration. PbI₂ is sparingly soluble → redissolves in hot water.' },
      { id: 'LP11', eq: '2HgCl₂ + SnCl₂ → Hg₂Cl₂↓ (white) + SnCl₄',                               tip: 'SnCl₂ reduces HgCl₂ (Hg+2) → Hg₂Cl₂ (Hg+1, calomel, white ppt). First step of SnCl₂ test for Hg²⁺.' },
      { id: 'LP12', eq: 'Hg₂Cl₂ + SnCl₂(excess) → 2Hg↓ (black) + SnCl₄',                          tip: 'Excess SnCl₂ reduces Hg₂Cl₂ further → Hg metal (black). White ppt → grey → black. Confirmatory test for Hg²⁺ AND SnCl₂ as reducing agent.' },
      { id: 'LP13', eq: 'Na₂SO₃ + S → Na₂S₂O₃ (preparation of sodium thiosulfate)',                 tip: 'Lab prep of sodium thiosulfate (hypo): Na₂SO₃ + S → Na₂S₂O₃. Boil together. S₂O₃²⁻ = SO₃²⁻ with one O replaced by S.' },
      { id: 'LP14', eq: 'HgCl₂ + 2KI → HgI₂↓ (red/scarlet) + 2KCl',                               tip: 'Mercury(II) iodide is red/scarlet precipitate. Soluble in excess KI → K₂[HgI₄] (Nessler\'s reagent, yellow-brown). Important in NH₃ detection.' },
      { id: 'LP15', eq: 'HgI₂ + 2KI → K₂[HgI₄] (Nessler\'s reagent)',                              tip: 'Nessler\'s reagent = alkaline K₂[HgI₄]. NH₃ + Nessler\'s → brown ppt (HgO·Hg(NH₂)I). Used to test for NH₃/NH₄⁺.' },
      { id: 'LP16', eq: 'Cu²⁺ + 4NH₃ → [Cu(NH₃)₄]²⁺ (deep blue, tetraamminecopper(II))',           tip: 'DEEP BLUE TEST for Cu²⁺! Add excess NH₃ to Cu²⁺ solution → vivid deep blue [Cu(NH₃)₄]²⁺. Pale blue Cu(OH)₂ ppt dissolves → deep blue. Classic distinction.' },
      { id: 'LP17', eq: 'Fe³⁺ + 3SCN⁻ → [Fe(SCN)₃] (blood red, test for Fe³⁺)',                    tip: 'BLOOD RED test for Fe³⁺! Add KSCN (potassium thiocyanate) to Fe³⁺ solution → blood red [Fe(SCN)₃]. Extremely sensitive. Any Fe³⁺ instantly → blood red.' },
      { id: 'LP18', eq: 'K₄[Fe(CN)₆] + 2FeCl₃ → Fe₄[Fe(CN)₆]₃↓ + 12KCl (Prussian blue)',        tip: 'PRUSSIAN BLUE test for Fe³⁺! Potassium ferrocyanide K₄[Fe(CN)₆] + Fe³⁺ → deep blue precipitate. Prussian blue = Fe₄[Fe(CN)₆]₃. Classic analytical test.' },
      { id: 'LP19', eq: 'K₃[Fe(CN)₆] + 3FeSO₄ → Fe₃[Fe(CN)₆]₂↓ + 3K₂SO₄ (Turnbull\'s blue)',    tip: 'TURNBULL\'S BLUE test for Fe²⁺! Potassium ferricyanide K₃[Fe(CN)₆] + Fe²⁺ → deep blue ppt. (Prussian and Turnbull\'s blue are actually the same compound now known.)' },
      { id: 'LP20', eq: 'Ag⁺ + 2NH₃ → [Ag(NH₃)₂]⁺ (Tollens\' reagent)',                           tip: 'TOLLENS\' REAGENT formation. Ag⁺ + NH₃ → diammine silver(I) complex. Used in Tollens\' test for aldehydes: [Ag(NH₃)₂]⁺ + RCHO → Ag↓ (silver mirror) + RCOOH.' },
      { id: 'LP21', eq: 'FeCl₃ + 3NaOH → Fe(OH)₃↓ (red-brown) + 3NaCl',                           tip: 'Fe³⁺ + NaOH → red-brown Fe(OH)₃ precipitate. Insoluble in excess NaOH (not amphoteric). Distinguishes Fe³⁺ from Al³⁺ (Al(OH)₃ dissolves in excess NaOH).' },
      { id: 'LP22', eq: 'FeCl₂ + 2NaOH → Fe(OH)₂↓ (dirty green) + 2NaCl',                         tip: 'Fe²⁺ + NaOH → dirty green Fe(OH)₂. Rapidly turns red-brown on standing in air (4Fe(OH)₂ + O₂ + 2H₂O → 4Fe(OH)₃). Distinguish Fe²⁺ from Fe³⁺!' },
      { id: 'LP23', eq: 'NaHCO₃ + HCl → NaCl + H₂O + CO₂ (baking soda + acid)',                   tip: 'Baking soda + any acid → CO₂ effervescence. Simple test for HCO₃⁻. NaHCO₃ is less alkaline than Na₂CO₃ — only weak base.' },
      { id: 'LP24', eq: 'H₂O₂ + O₃ → 2O₂ + H₂O (mutual oxidant-reductant)',                       tip: 'H₂O₂ + O₃ react with each other — H₂O₂ acts as REDUCTANT reducing O₃ to O₂. H₂O₂ is oxidised to O₂. Both are strong oxidants but H₂O₂ reduces stronger O₃.' },
    ],
  },
  {
    id: 'carbon_industrial',
    name: 'Carbon, Silicon & Industrial Gas Reactions',
    desc: 'Boudouard reaction, water gas, acetylene prep, silicon chemistry, gypsum',
    reactions: [
      { id: 'CI01', eq: 'C + CO₂ → 2CO (Boudouard reaction, ~1000°C)',                               tip: 'BOUDOUARD REACTION! C reduces CO₂ to CO at high temp. Opposite of combustion (C+O₂→CO₂). Crucial in blast furnace — CO₂ formed reacts with more coke → 2CO.' },
      { id: 'CI02', eq: 'C + H₂O(steam) → CO + H₂ (water gas, ~1000°C)',                            tip: 'WATER GAS! Steam passed over hot coke → CO + H₂ (syn gas). Industrial H₂ source. Also: C + 2H₂O → CO₂ + 2H₂ (at lower temp).' },
      { id: 'CI03', eq: 'CO + H₂O(steam) → CO₂ + H₂ (water gas shift reaction)',                    tip: 'WATER GAS SHIFT! CO + H₂O → CO₂ + H₂. Key step in industrial H₂ production. Used to increase H₂:CO ratio. Catalyst: Fe₂O₃/Cr₂O₃.' },
      { id: 'CI04', eq: 'CO + Cl₂ → COCl₂ (phosgene, in sunlight or activated C)',                  tip: 'CO + Cl₂ → COCl₂ (PHOSGENE — extremely toxic war gas!). Used as reagent in organic synthesis. Sunlight/activated carbon catalyst.' },
      { id: 'CI05', eq: 'CaC₂ + 2H₂O → Ca(OH)₂ + C₂H₂ (acetylene/ethyne)',                        tip: 'ACETYLENE PREPARATION! Calcium carbide + water → acetylene (C₂H₂) + slaked lime. Classic lab/industrial method. Used in welding torches.' },
      { id: 'CI06', eq: 'CaC₂ + N₂ → CaCN₂ + C (cyanamide process, 1100°C)',                       tip: 'Cyanamide process: CaC₂ reacts with N₂ at high temp → calcium cyanamide (CaCN₂) + carbon. CaCN₂ + H₂O → CaCO₃ + NH₃ (nitrogen fertiliser).' },
      { id: 'CI07', eq: 'Si + 2NaOH + H₂O → Na₂SiO₃ + 2H₂',                                        tip: 'Silicon dissolves in NaOH (like Al, amphoteric-ish). Si + NaOH → sodium silicate + H₂ gas. Si does NOT react with HCl/HNO₃ but DOES react with NaOH and HF.' },
      { id: 'CI08', eq: 'SiO₂ + 2NaOH → Na₂SiO₃ + H₂O (silica in alkali)',                         tip: 'Silica (SiO₂) dissolves in hot conc NaOH → sodium silicate (waterglass). Despite SiO₂+H₂O = no reaction, SiO₂+NaOH DOES react!' },
      { id: 'CI09', eq: 'SiO₂ + 4HF → SiF₄ + 2H₂O (silica dissolves ONLY in HF)',                 tip: 'SiO₂ is resistant to all acids EXCEPT HF! SiO₂ + HF → SiF₄ (gas) + H₂O. HF stored in plastic/wax containers, never glass!' },
      { id: 'CI10', eq: 'CaSO₄·2H₂O → CaSO₄·½H₂O + 3/2H₂O (heat 120–130°C, plaster of Paris)',   tip: 'PLASTER OF PARIS made by heating gypsum (CaSO₄·2H₂O) at 120-130°C. Loses 3/2 water molecules. Use above 150°C → anhydrous dead-burnt plaster.' },
      { id: 'CI11', eq: 'CaSO₄·½H₂O + 3/2H₂O → CaSO₄·2H₂O (setting of plaster of Paris)',        tip: 'Plaster of Paris SETS by absorbing water → back to gypsum. Exothermic → mixture warms while setting. Expands slightly → fills mould exactly.' },
      { id: 'CI12', eq: '4FeS₂ + 11O₂ → 2Fe₂O₃ + 8SO₂ (roasting of pyrite, Contact Process step 1)', tip: 'ROASTING IRON PYRITE (FeS₂) is Contact Process Step 1! Pyrite provides SO₂ industrially. Fe₂O₃ is a byproduct.' },
      { id: 'CI13', eq: '2H₂S + 3O₂(excess) → 2SO₂ + 2H₂O (complete combustion)',                  tip: 'H₂S burns in excess O₂ → SO₂ + H₂O. Limited O₂: 2H₂S + O₂ → 2S + 2H₂O (partial). Burning H₂S smell is pungent SO₂.' },
      { id: 'CI14', eq: 'SO₂ + Br₂ + 2H₂O → H₂SO₄ + 2HBr',                                        tip: 'SO₂ is oxidised by Br₂ in water → H₂SO₄ + HBr. SO₂ (S+4) → H₂SO₄ (S+6). Br₂ is the oxidant here.' },
      { id: 'CI15', eq: 'I₂ + Cl₂ → 2ICl (iodine monochloride, interhalogen)',                      tip: 'Interhalogen compound! ICl is a brown-black liquid. Cl₂ is stronger oxidant → I₂ → ICl. I₂ + Cl₂(excess) → 2ICl₃ (iodine trichloride, yellow solid).' },
    ],
  },
  {
    id: 'solvay_misc',
    name: 'Solvay Process, Gypsum & Miscellaneous Industrial',
    desc: 'Solvay Process for Na₂CO₃, carbonate chemistry, and miscellaneous JEE reactions',
    reactions: [
      { id: 'SV01', eq: 'NaCl + NH₃ + CO₂ + H₂O → NaHCO₃↓ + NH₄Cl (Solvay Process)',              tip: 'SOLVAY PROCESS for Na₂CO₃! NaHCO₃ precipitates because it is least soluble. Then heated to give Na₂CO₃. NH₄Cl is recovered and treated with Ca(OH)₂ to regenerate NH₃.' },
      { id: 'SV02', eq: '2NaHCO₃ → Na₂CO₃ + H₂O + CO₂ (heat)',                                     tip: 'Baking soda (NaHCO₃) decomposes on heating → washing soda (Na₂CO₃) + H₂O + CO₂. Why baking soda makes cakes rise! Also occurs in Solvay Process step 2.' },
      { id: 'SV03', eq: 'Na₂CO₃ + CO₂ + H₂O → 2NaHCO₃',                                            tip: 'Washing soda + CO₂ + H₂O → baking soda. Reverse of SV02. Used to make NaHCO₃ from Na₂CO₃ solution.' },
      { id: 'SV04', eq: 'Na₂CO₃ + H₂O ⇌ NaOH + NaHCO₃ (hydrolysis of Na₂CO₃)',                    tip: 'Sodium carbonate is a salt of strong base (NaOH) and weak acid (H₂CO₃) → alkaline solution. Na₂CO₃ is used as a cleaning agent (washing soda).' },
      { id: 'SV05', eq: 'Na₂CO₃ + Ca(OH)₂ → CaCO₃↓ + 2NaOH (causticisation)',                     tip: 'CAUSTICISATION! Na₂CO₃ + lime → CaCO₃ precipitate + NaOH solution. Used to convert carbonate → hydroxide industrially.' },
      { id: 'SV06', eq: 'CaCO₃ + 2NH₄Cl → CaCl₂ + 2NH₃↑ + H₂O + CO₂ (Solvay NH₃ recovery)',     tip: 'Solvay NH₃ recovery step: ammonium chloride (by-product) + limestone → NH₃ regenerated + CaCl₂ + CO₂. NH₃ is recycled in Solvay.' },
      { id: 'SV07', eq: 'Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂ (carbonate + acid)',                   tip: 'Carbonate + acid → salt + CO₂ + H₂O. Effervescence of CO₂ is the test for CO₃²⁻. Distinguish from SO₃²⁻ by smell (SO₂ vs CO₂).' },
      { id: 'SV08', eq: 'CaCO₃ + H₂SO₄(dil.) → CaSO₄↓ + H₂O + CO₂ (passivation)',                tip: 'CaCO₃ + H₂SO₄ initially reacts then stops. CaSO₄ is sparingly soluble → coats surface → reaction ceases. Why HCl (not H₂SO₄) is used in lab CO₂ prep.' },
      { id: 'SV09', eq: 'Fe₂O₃ + 3H₂ → 2Fe + 3H₂O (reduction by hydrogen)',                       tip: 'Iron oxide reduced by H₂. Used in direct reduction of iron. Compare: Fe₂O₃ + 3CO → 2Fe + 3CO₂ (blast furnace). Both are important reductions.' },
      { id: 'SV10', eq: '3Fe + 4H₂O(steam) ⇌ Fe₃O₄ + 4H₂ (reversible, used in H₂ production)',   tip: 'The steam-iron process for producing H₂! Reversible: Fe + steam → Fe₃O₄ + H₂. Used historically. Key in industrial H₂ production.' },
    ],
  },
  {
    id: 'extraction',
    name: 'Metallurgical Extraction — Mond, Van Arkel, Roasting',
    desc: 'Purification of metals and ore extraction reactions — Mond, Van Arkel, self-reduction',
    reactions: [
      { id: 'EX01', eq: 'Ni + 4CO → Ni(CO)₄ (Mond process, 50–60°C)',                               tip: 'MOND PROCESS for pure Ni! Ni + CO at 50-60°C → volatile Ni(CO)₄. Only Ni reacts this way at this temp — selective for Ni.' },
      { id: 'EX02', eq: 'Ni(CO)₄ → Ni + 4CO (Mond decomposition, ~230°C)',                          tip: 'Step 2: Ni(CO)₄ decomposes on hot Ni sphere at 230°C → ultra-pure Ni deposits. CO is recycled. Very high purity (99.99%).' },
      { id: 'EX03', eq: 'Ti + 2I₂ → TiI₄ (Van Arkel method, ~250°C)',                               tip: 'VAN ARKEL METHOD for Ti! Ti + I₂ at ~250°C → volatile TiI₄. Impure Ti reacts, pure Ti does not — selective volatilisation.' },
      { id: 'EX04', eq: 'TiI₄ → Ti + 2I₂ (Van Arkel decomposition, ~1400°C on W filament)',         tip: 'Step 2: TiI₄ decomposes on hot W filament at 1400°C → ultra-pure Ti metal. I₂ recycled. Also works for Zr, Hf.' },
      { id: 'EX05', eq: '2Cu₂S + 3O₂ → 2Cu₂O + 2SO₂ (partial roasting of copper ore)',             tip: 'Roasting copper ore Cu₂S with limited O₂ → Cu₂O + SO₂. Sets up for self-reduction.' },
      { id: 'EX06', eq: 'Cu₂S + 2Cu₂O → 6Cu + SO₂ (self-reduction, blister copper)',               tip: 'SELF-REDUCTION! Cu₂S reduces Cu₂O → blister copper (~98%). No external reducing agent. Similar to Pb self-reduction.' },
      { id: 'EX07', eq: '2PbS + 3O₂ → 2PbO + 2SO₂ (roasting of galena)',                           tip: 'Lead ore (galena, PbS) roasting. PbO then reduced: PbO + C → Pb + CO. Or self-reduction: PbO + PbS → 3Pb + SO₂.' },
      { id: 'EX08', eq: 'PbO + PbS → 3Pb + SO₂ (self-reduction of lead)',                           tip: 'Lead self-reduction — PbS reduces PbO → Pb metal + SO₂. No separate reducing agent needed. Analogous to Cu₂S + Cu₂O.' },
      { id: 'EX09', eq: '2ZnS + 3O₂ → 2ZnO + 2SO₂ (roasting of zinc blende)',                      tip: 'Roasting zinc blende. ZnO reduced by coke: ZnO + C → Zn + CO at 1000°C. Zn distils off as vapour (b.p. 907°C) → condensed.' },
      { id: 'EX10', eq: 'ZnO + C → Zn + CO (carbon reduction, ~1000°C)',                            tip: 'Zinc extracted from ZnO by coke reduction. Zn boils (b.p. 907°C) and is collected by condensation. Carbon reduction works because Zn b.p. < reduction temp.' },
      { id: 'EX11', eq: '2HgS + 3O₂ → 2HgO + 2SO₂; 2HgO → 2Hg + O₂ (roasting cinnabar)',         tip: 'Mercury extracted from cinnabar by roasting. HgO decomposes at 300°C → Hg (liquid). Most easily extracted metal — just heat ore in air!' },
      { id: 'EX12', eq: 'Al₂O₃ + 2NaOH(aq.) → 2NaAlO₂ + H₂O (Bayer process leaching)',            tip: 'BAYER PROCESS Step 1: Bauxite dissolved in hot NaOH → NaAlO₂. Fe₂O₃ and SiO₂ impurities remain. Then CO₂ → Al(OH)₃ precipitates → calcined → Al₂O₃ → electrolysis.' },
      { id: 'EX13', eq: '2Al₂O₃ → 4Al + 3O₂ (Hall-Héroult electrolysis, dissolved in cryolite)',   tip: 'HALL-HÉROULT PROCESS! Al₂O₃ dissolved in molten cryolite (Na₃AlF₆) → electrolysis at 950°C → Al at cathode, O₂ at anode. Most energy-intensive extraction process.' },
    ],
  },
  {
    id: 'advanced_pblock',
    name: 'Advanced p-block — Lewis Acid-Base, Comproportionation & Special',
    desc: 'JEE Advanced level reactions: Lewis adducts, fluorocomplexes, disproportionation, interhalogen',
    reactions: [
      { id: 'AD01', eq: 'BF₃ + NH₃ → F₃B←NH₃ (Lewis acid-base adduct)',                            tip: 'CLASSIC Lewis acid-base! BF₃ is a Lewis ACID (accepts lone pair), NH₃ is a Lewis BASE (donates lone pair). The B-N coordinate bond forms. B goes from sp² → sp³.' },
      { id: 'AD02', eq: 'BF₃ + F⁻ → [BF₄]⁻ (tetrafluoroborate)',                                   tip: 'BF₃ + F⁻ → [BF₄]⁻. BF₃ accepts F⁻ (Lewis acid). [BF₄]⁻ is tetrahedral, sp³. This is how H[BF₄] (fluoroboric acid) forms when BF₃ hydrolyzes (R77).' },
      { id: 'AD03', eq: 'SiF₄ + 2F⁻ → [SiF₆]²⁻ (hexafluorosilicate)',                             tip: 'SiF₄ (Lewis acid, empty d-orbital) + 2F⁻ → [SiF₆]²⁻ (octahedral). SiF₄ can expand its coordination (unlike CF₄). H₂SiF₆ (fluorosilicic acid) dissolves glass!' },
      { id: 'AD04', eq: 'SiF₄ + 2HF → H₂SiF₆ (fluorosilicic acid)',                               tip: 'SiF₄ reacts with HF (or HF + H₂O) → H₂SiF₆. Formed when HF etches glass. H₂SiF₆ is a strong acid used in water fluoridation.' },
      { id: 'AD05', eq: 'AlCl₃ + Cl⁻ → [AlCl₄]⁻ (tetrachloroaluminate)',                          tip: 'AlCl₃ is a strong Lewis acid → accepts Cl⁻ → [AlCl₄]⁻. This is the active catalyst in Friedel-Crafts reactions (AlCl₃ activates RCl).' },
      { id: 'AD06', eq: 'PCl₃ + Cl₂ → PCl₅; PCl₅ ⇌ PCl₃ + Cl₂ (equilibrium)',                    tip: 'PCl₅ forms by Cl₂ addition to PCl₃. Dissociates at high temp (R193, PR07). In solid state PCl₅ exists as [PCl₄]⁺[PCl₆]⁻ ionic form!' },
      { id: 'AD07', eq: '[PCl₄]⁺[PCl₆]⁻ (PCl₅ in solid state — ionic form!)',                     tip: 'Advanced: Solid PCl₅ is NOT molecular PCl₅ — it exists as [PCl₄]⁺[PCl₆]⁻ (tetrachlorophosphonium hexachlorophosphate)! Tetrahedral cation + octahedral anion.' },
      { id: 'AD08', eq: 'NOCl + H₂O → HNO₂ + HCl (hydrolysis of nitrosyl chloride)',              tip: 'Nitrosyl chloride (NOCl, yellow toxic gas) hydrolyzes to HNO₂ + HCl. HNO₂ is unstable → disproportionates (NR18). Formed by: 2NO + Cl₂ → 2NOCl.' },
      { id: 'AD09', eq: '2Cu⁺(aq) → Cu(s) + Cu²⁺(aq) (disproportionation)',                       tip: 'Cu⁺ is UNSTABLE in aqueous solution — instantly disproportionates. Cu(+1) → Cu(0) + Cu(+2). This is why Cu⁺ only exists as INSOLUBLE compounds (CuCl, CuI, Cu₂O). If you dissolve CuCl in water → Cu²⁺ + Cu!' },
      { id: 'AD10', eq: 'Fe + 2FeCl₃ → 3FeCl₂ (comproportionation)',                              tip: 'Iron COMPROPORTIONATION: Fe(0) + Fe(+3) → Fe(+2). Opposite of disproportionation. Fe dissolves in FeCl₃ solution. Used to prepare FeCl₂ by adding excess Fe to FeCl₃.' },
      { id: 'AD11', eq: 'Pb + 2NaOH(conc) → Na₂PbO₂ + H₂ (Pb is amphoteric)',                    tip: 'Lead is AMPHOTERIC — rarely remembered! Pb + conc NaOH → Na₂PbO₂ (sodium plumbite) + H₂. Amphoteric metals: Pb, Sn, Zn, Al (PSZA). Sb, Bi also somewhat amphoteric.' },
      { id: 'AD12', eq: '4NOCl → 2NO₂ + 2NO + Cl₂ (NOCl decomposition)',                         tip: 'NOCl is unstable and decomposes. Shows interconversion between N oxides. Used in some industrial processes.' },
      { id: 'AD13', eq: 'H₂O₂ + O₃ → 2O₂ + H₂O (H₂O₂ reduces O₃)',                              tip: 'H₂O₂ acts as REDUCTANT towards O₃ (stronger oxidant). H₂O₂ is oxidised to O₂; O₃ reduced to O₂. Both products are O₂! Net: O₃ + H₂O₂ → 2O₂ + H₂O.' },
    ],
  },
];
